"""Milestone-2 emitter tests: --check parity, file manifest, content spot-checks.

These guard the Python->C++ codegen contract without a compiler: the checked-in
``lib/generated/`` must be byte-identical to a fresh emit, the expected file set
must be present, and a few load-bearing shapes (the Geom struct's fields, the
ActuatorAny union child-list type, presence wrapping, the field-count constant)
must appear in the output. The C++ side (compile, run, property tests) is driven
by protospec/lib/CMakeLists.txt and protospec/lib/test/test_model.cc.
"""

from __future__ import annotations

import os

from protospec_gen import emit, parse_spec

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN_DIR = os.path.join(ROOT, "lib", "generated")

EXPECTED_FILES = {
    "types.h",
    "types.cc",
    "visit.h",
    "reflect.h",
    "reflect.cc",
    "keywords.h",
    "keywords.cc",
    "defaults.h",
    "defaults.cc",
    "xml_binding.h",
    "xml_binding.cc",
    # ProtoSpec->mjSpec field-mapping layer (emitted by emit_mjs, part of the
    # same emit invocation and the same --check gate).
    "mjs_binding.h",
    "mjs_binding.cc",
}


def _generated() -> dict[str, str]:
    return emit.generate()


def test_generate_produces_expected_manifest():
    files = _generated()
    assert set(files) == EXPECTED_FILES


def test_checked_in_matches_fresh_emit():
    """The checked-in lib/generated/ is byte-identical to a fresh emit (the
    same invariant `python -m protospec_gen.emit --check` enforces)."""
    files = _generated()
    for name, content in files.items():
        path = os.path.join(GEN_DIR, name)
        assert os.path.exists(path), f"{name} is not checked in"
        with open(path, "r", encoding="utf-8", newline="") as fh:
            current = fh.read().replace("\r\n", "\n")
        assert current == content, (
            f"{name} is stale; re-run `python -m protospec_gen.emit`"
        )


def test_every_file_carries_the_banner():
    # The core emitter and the mjs_binding emitter carry distinct attributions;
    # both are "generated by protospec_gen.*" do-not-edit banners.
    for content in _generated().values():
        first = content.splitlines()[0]
        assert first.startswith("// Generated by protospec_gen.")
        assert first.endswith("do not edit.")


def test_geom_struct_contains_expected_fields():
    types_h = _generated()["types.h"]
    # Isolate the Geom struct definition.
    start = types_h.index("struct Geom {")
    body = types_h[start : types_h.index("\n};", start)]
    # Presence-tracked scalar, enum, ref, variant, arity, and child-list shapes.
    assert "ps::opt<GeomType> type" in body
    assert "ps::opt<ps::Ref<Material>> material" in body
    assert "ps::opt<ps::InlineVec<double, 3>> friction" in body  # range arity
    assert "ps::opt<GeomShape> shape" in body  # variant field
    assert "std::vector<std::unique_ptr<PluginRef>> plugin" in body  # child list
    assert "std::uint64_t serial" in body  # creation serial
    assert "ps::SourceLoc loc" in body  # provenance


def test_actuator_union_child_list_type_exists():
    types_h = _generated()["types.h"]
    assert "struct ActuatorAny {" in types_h
    # The container element carries the one ordered heterogeneous list.
    start = types_h.index("struct Actuator {")
    body = types_h[start : types_h.index("\n};", start)]
    assert "std::vector<ActuatorAny> actuators" in body


def test_field_count_constant_matches_ast():
    """The generated kFieldCount_<Element> constants equal the AST field counts;
    this is the constant the C++ reflection self-check pins against."""
    schema = parse_spec(os.path.join(ROOT, "schema", "mujoco.spec")).to_json()
    reflect_h = _generated()["reflect.h"]
    for e in schema["elements"]:
        n = len(e["fields"])
        assert f"kFieldCount_{e['name']} = {n};" in reflect_h


def test_keyword_table_sanitizes_reserved_enumerators():
    keywords_cc = _generated()["keywords.cc"]
    # `auto` is a C++ keyword: enumerator sanitized, MJCF string preserved.
    assert 'case TriState::auto_: return "auto";' in keywords_cc


def test_xml_binding_covers_every_element():
    """Every element gets an ElementBinding row (schema-complete: a later IO
    family reuses these rows with no emitter change)."""
    schema = parse_spec(os.path.join(ROOT, "schema", "mujoco.spec")).to_json()
    binding_cc = _generated()["xml_binding.cc"]
    for e in schema["elements"]:
        assert f"ElementType::{e['name']}," in binding_cc
    n = len(schema["elements"])
    # One ElementBinding literal per element in the kBindings table.
    start = binding_cc.index("constexpr ElementBinding kBindings[]")
    table = binding_cc[start : binding_cc.index("\n};", start)]
    assert table.count("{ElementType::") == n


def test_xml_binding_routes_variant_arms_and_worldbody():
    binding_cc = _generated()["xml_binding.cc"]
    # The surviving GeomShape variant routes its fromto arm (Q-FROMTO KEEP).
    assert '{"fromto", "fromto"}' in binding_cc
    # Q-ORIENT canonicalization: euler/axisangle/... are read-only input aliases
    # of the canonical quat (routed via the orientation resolver), not variant arms.
    assert '{"euler", "orientation"}' in binding_cc
    assert '{"axisangle", "orientation"}' in binding_cc
    # The worldbody child list diverges from the <body> tag (MJCF body-row share).
    assert '{"worldbody", "worldbody", "Body", ElementType::Body, false}' in binding_cc
    # Body-in-body recursion (and geom/joint/frame/macro interleave) is routed
    # through the ordered BodyChildAny union child, not a per-<body> list.
    assert '{"subtree", "", "BodyChildAny", ElementType::' in binding_cc


def test_xml_binding_marks_angle_units():
    binding_cc = _generated()["xml_binding.cc"]
    # Joint reference angles carry the unit=angle flag (deg->rad at IO, Q-ANGLE).
    # Row tail is unit_angle, keyword_set, element_text, resolver (empty when the
    # field is not canonicalized -- a plain angle ref has no resolver).
    start = binding_cc.index("kAttrs_Joint[]")
    body = binding_cc[start : binding_cc.index("};", start)]
    ref_row = [ln for ln in body.splitlines() if '"ref",' in ln][0]
    assert ref_row.rstrip().endswith('true, false, false, ""},')  # unit_angle, no resolver


def test_xml_binding_marks_resolved_and_input_aliases():
    binding_cc = _generated()["xml_binding.cc"]
    # The canonical quat attribute carries its resolver name (parse-end
    # canonicalization); the reader skips the plain read and dispatches off this
    # name. Row tail is unit_angle, keyword_set, element_text, resolver.
    start = binding_cc.index("kAttrs_Body[]")
    body = binding_cc[start : binding_cc.index("};", start)]
    quat_row = [ln for ln in body.splitlines() if '"quat",' in ln][0]
    assert quat_row.rstrip().endswith('false, false, false, "orientation"},')
    # Inertial routes fullinertia through the inertia resolver (-> diaginertia+iquat).
    assert '{"fullinertia", "inertia"}' in binding_cc


def test_defaults_only_where_idl_has_them():
    defaults_cc = _generated()["defaults.cc"]
    start = defaults_cc.index("void ApplyDefault(Geom& e)")
    body = defaults_cc[start : defaults_cc.index("\n}", start)]
    assert "e.type = GeomType::sphere;" in body
    assert "e.contype = 1;" in body
    assert "e.mass" not in body  # no IDL default -> not applied
