# CMake generated Testfile for 
# Source directory: C:/Users/jonat/Documents/protospec/cpp
# Build directory: C:/Users/jonat/Documents/protospec/cpp/build_wave3
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[protospec_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/Debug/protospec_tests.exe")
  set_tests_properties([=[protospec_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;102;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[protospec_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/Release/protospec_tests.exe")
  set_tests_properties([=[protospec_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;102;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[protospec_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/MinSizeRel/protospec_tests.exe")
  set_tests_properties([=[protospec_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;102;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[protospec_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/RelWithDebInfo/protospec_tests.exe")
  set_tests_properties([=[protospec_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;102;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
else()
  add_test([=[protospec_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[protospec_io_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/Debug/protospec_io_tests.exe")
  set_tests_properties([=[protospec_io_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;111;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[protospec_io_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/Release/protospec_io_tests.exe")
  set_tests_properties([=[protospec_io_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;111;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[protospec_io_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/MinSizeRel/protospec_io_tests.exe")
  set_tests_properties([=[protospec_io_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;111;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[protospec_io_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/RelWithDebInfo/protospec_io_tests.exe")
  set_tests_properties([=[protospec_io_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;111;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
else()
  add_test([=[protospec_io_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[protospec_validate_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/Debug/protospec_validate_tests.exe")
  set_tests_properties([=[protospec_validate_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;120;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[protospec_validate_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/Release/protospec_validate_tests.exe")
  set_tests_properties([=[protospec_validate_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;120;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[protospec_validate_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/MinSizeRel/protospec_validate_tests.exe")
  set_tests_properties([=[protospec_validate_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;120;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[protospec_validate_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/RelWithDebInfo/protospec_validate_tests.exe")
  set_tests_properties([=[protospec_validate_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;120;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
else()
  add_test([=[protospec_validate_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[protospec_bridge_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/Debug/protospec_bridge_tests.exe")
  set_tests_properties([=[protospec_bridge_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;247;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[protospec_bridge_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/Release/protospec_bridge_tests.exe")
  set_tests_properties([=[protospec_bridge_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;247;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[protospec_bridge_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/MinSizeRel/protospec_bridge_tests.exe")
  set_tests_properties([=[protospec_bridge_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;247;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[protospec_bridge_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/RelWithDebInfo/protospec_bridge_tests.exe")
  set_tests_properties([=[protospec_bridge_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;247;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
else()
  add_test([=[protospec_bridge_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[protospec_sdk_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/Debug/protospec_sdk_tests.exe")
  set_tests_properties([=[protospec_sdk_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;266;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[protospec_sdk_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/Release/protospec_sdk_tests.exe")
  set_tests_properties([=[protospec_sdk_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;266;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[protospec_sdk_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/MinSizeRel/protospec_sdk_tests.exe")
  set_tests_properties([=[protospec_sdk_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;266;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[protospec_sdk_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/RelWithDebInfo/protospec_sdk_tests.exe")
  set_tests_properties([=[protospec_sdk_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;266;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
else()
  add_test([=[protospec_sdk_tests]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[protospec_compile_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/Debug/protospec_compile_tests.exe")
  set_tests_properties([=[protospec_compile_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;306;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[protospec_compile_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/Release/protospec_compile_tests.exe")
  set_tests_properties([=[protospec_compile_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;306;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[protospec_compile_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/MinSizeRel/protospec_compile_tests.exe")
  set_tests_properties([=[protospec_compile_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;306;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[protospec_compile_tests]=] "C:/Users/jonat/Documents/protospec/cpp/build_wave3/RelWithDebInfo/protospec_compile_tests.exe")
  set_tests_properties([=[protospec_compile_tests]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;306;add_test;C:/Users/jonat/Documents/protospec/cpp/CMakeLists.txt;0;")
else()
  add_test([=[protospec_compile_tests]=] NOT_AVAILABLE)
endif()
subdirs("harness")
