mujoco_version "3.10.0"

# ==========================================================================
# ProtoSpec IDL schema for MuJoCo MJCF (generated by
# tools/bootstrap/draft_schema.py, then hand-curated -- see plan Section 5).
# ==========================================================================

# --- Enums (keyword tables from the MJCF mjMap[] surface) ------------------

enum AngleUnit {
  radian         = "radian"
  degree         = "degree"
}

enum BiasType {
  none           = "none"
  affine         = "affine"
  muscle         = "muscle"
  dcmotor        = "dcmotor"
  user           = "user"
}

enum BodySleep {
  auto           = "auto"
  never          = "never"
  allowed        = "allowed"
  init           = "init"
}

enum CamLightMode {
  fixed          = "fixed"
  track          = "track"
  trackcom       = "trackcom"
  targetbody     = "targetbody"
  targetbodycom  = "targetbodycom"
}

enum CameraOutput {
  rgb            = "rgb"
  depth          = "depth"
  distance       = "distance"
  normal         = "normal"
  segmentation   = "segmentation"
}

enum CameraProjection {
  perspective    = "perspective"
  orthographic   = "orthographic"
}

enum ColorSpace {
  auto           = "auto"
  linear         = "linear"
  sRGB           = "sRGB"
}

enum CompositeType {
  particle       = "particle"
  grid           = "grid"
  rope           = "rope"
  loop           = "loop"
  cable          = "cable"
  cloth          = "cloth"
}

enum Cone {
  pyramidal      = "pyramidal"
  elliptic       = "elliptic"
}

enum ContactReduce {
  none           = "none"
  mindist        = "mindist"
  maxforce       = "maxforce"
  netforce       = "netforce"
}

enum Coordinate {
  local          = "local"
  global         = "global"
}

enum DataType {
  real           = "real"
  positive       = "positive"
  axis           = "axis"
  quaternion     = "quaternion"
}

enum DcMotorInput {
  voltage        = "voltage"
  position       = "position"
  velocity       = "velocity"
}

enum DynType {
  none           = "none"
  integrator     = "integrator"
  filter         = "filter"
  filterexact    = "filterexact"
  muscle         = "muscle"
  dcmotor        = "dcmotor"
  user           = "user"
}

enum Elastic2D {
  none           = "none"
  bend           = "bend"
  stretch        = "stretch"
  both           = "both"
}

enum FlexDof {
  full           = "full"
  radial         = "radial"
  trilinear      = "trilinear"
  quadratic      = "quadratic"
  twod           = "2d"
}

enum FlexEquality {
  false_         = "false"
  true_          = "true"
  vert           = "vert"
  strain         = "strain"
}

enum FlexSelfCollide {
  none           = "none"
  narrow         = "narrow"
  bvh            = "bvh"
  sap            = "sap"
  auto           = "auto"
}

enum FlexcompType {
  grid           = "grid"
  box            = "box"
  cylinder       = "cylinder"
  ellipsoid      = "ellipsoid"
  square         = "square"
  disc           = "disc"
  circle         = "circle"
  mesh           = "mesh"
  gmsh           = "gmsh"
  direct         = "direct"
}

enum FluidShape {
  none           = "none"
  ellipsoid      = "ellipsoid"
}

enum GainType {
  fixed          = "fixed"
  affine         = "affine"
  muscle         = "muscle"
  dcmotor        = "dcmotor"
  user           = "user"
}

enum GeomType {
  plane          = "plane"
  hfield         = "hfield"
  sphere         = "sphere"
  capsule        = "capsule"
  ellipsoid      = "ellipsoid"
  cylinder       = "cylinder"
  box            = "box"
  mesh           = "mesh"
  sdf            = "sdf"
}

enum InertiaFromGeom {
  false_         = "false"
  true_          = "true"
  auto           = "auto"
}

enum Integrator {
  Euler          = "Euler"
  RK4            = "RK4"
  implicit       = "implicit"
  implicitfast   = "implicitfast"
}

enum InterpType {
  zoh            = "zoh"
  linear         = "linear"
  cubic          = "cubic"
}

enum JacobianType {
  dense          = "dense"
  sparse         = "sparse"
  auto           = "auto"
}

enum JointType {
  free           = "free"
  ball           = "ball"
  slide          = "slide"
  hinge          = "hinge"
}

enum LRMode {
  none           = "none"
  muscle         = "muscle"
  muscleuser     = "muscleuser"
  all            = "all"
}

enum LightType {
  spot           = "spot"
  directional    = "directional"
  point          = "point"
  image          = "image"
}

enum MeshBuiltin {
  none           = "none"
  sphere         = "sphere"
  hemisphere     = "hemisphere"
  cone           = "cone"
  supertorus     = "supertorus"
  supersphere    = "supersphere"
  wedge          = "wedge"
  plate          = "plate"
}

enum MeshInertia {
  convex         = "convex"
  legacy         = "legacy"
  exact          = "exact"
  shell          = "shell"
}

enum NeedStage {
  none           = "none"
  pos            = "pos"
  vel            = "vel"
  acc            = "acc"
}

enum RayData {
  dist           = "dist"
  dir            = "dir"
  origin         = "origin"
  point          = "point"
  normal         = "normal"
  depth          = "depth"
}

enum SolverType {
  PGS            = "PGS"
  CG             = "CG"
  Newton         = "Newton"
}

enum TexRole {
  rgb            = "rgb"
  occlusion      = "occlusion"
  roughness      = "roughness"
  metallic       = "metallic"
  normal         = "normal"
  opacity        = "opacity"
  emissive       = "emissive"
  rgba           = "rgba"
  orm            = "orm"
}

enum TextureBuiltin {
  none           = "none"
  gradient       = "gradient"
  checker        = "checker"
  flat           = "flat"
}

enum TextureMark {
  none           = "none"
  edge           = "edge"
  cross          = "cross"
  random         = "random"
}

enum TextureType {
  twod           = "2d"
  cube           = "cube"
  skybox         = "skybox"
}

enum TriState {
  false_         = "false"
  true_          = "true"
  auto           = "auto"
}

# --- Orientation, shape and inertia variants (DR-3) -----------------------

struct Quat      { w : double  x : double  y : double  z : double }
struct AxisAngle { axis : double[3]  angle : double (unit=angle) }
struct XYAxes    { xyaxes : double[6] }
struct ZAxis     { zaxis : double[3] }
struct Euler     { angles : double[3] (unit=angle) }

variant Orientation {
  quat      : Quat        # unit quaternion (canonical form)
  axisangle : AxisAngle   # rotation axis + angle
  xyaxes    : XYAxes      # x and y axes
  zaxis     : ZAxis       # z axis (minimal rotation)
  euler     : Euler       # euler angles, sequence from compiler.eulerseq
}

struct Explicit { size : double[0..3] }
struct FromTo   { fromto : double[6] }
variant GeomShape {
  explicit : Explicit     # type-specific size, at the element's own pose
  fromto   : FromTo       # capsule/cylinder/box/ellipsoid endpoints
}

struct DiagInertia { diaginertia : double[3] }
struct FullInertia { fullinertia : double[6] }
variant InertiaSpec {
  diaginertia : DiagInertia   # diagonal inertia in the inertial frame
  fullinertia : FullInertia   # full (non-axis-aligned) inertia matrix
}

struct Fovy  { fovy : double (unit=angle) }
struct Focal { focal : double[2] }
variant CameraIntrinsics {
  fovy  : Fovy    # vertical field of view
  focal : Focal   # focal length (length units)
}

struct TexFile { file : string }
variant TextureSource {
  builtin : TextureBuiltin   # procedural generator
  file    : TexFile          # single image file (buffer form is API-only)
}

mixin Posed {
  pos    : double[3] = {0, 0, 0}   # position offset
  orient : variant Orientation     # quat | axisangle | xyaxes | zaxis | euler
}

# --- Unions (ordered heterogeneous child lists / any-of refs) -------------

union ActuatorAny =
    ActuatorGeneral
  | Motor
  | Position
  | Velocity
  | IntVelocity
  | Damper
  | Cylinder
  | Muscle
  | Adhesion
  | DcMotor
  | ActuatorPlugin

union SensorAny =
    Touch
  | Accelerometer
  | Velocimeter
  | Gyro
  | Force
  | Torque
  | Magnetometer
  | Camprojection
  | Rangefinder
  | Jointpos
  | Jointvel
  | Tendonpos
  | Tendonvel
  | Actuatorpos
  | Actuatorvel
  | Actuatorfrc
  | Jointactuatorfrc
  | Tendonactuatorfrc
  | Ballquat
  | Ballangvel
  | Jointlimitpos
  | Jointlimitvel
  | Jointlimitfrc
  | Tendonlimitpos
  | Tendonlimitvel
  | Tendonlimitfrc
  | Framepos
  | Framequat
  | Framexaxis
  | Frameyaxis
  | Framezaxis
  | Framelinvel
  | Frameangvel
  | Framelinacc
  | Frameangacc
  | Subtreecom
  | Subtreelinvel
  | Subtreeangmom
  | Insidesite
  | Distance
  | Normal
  | Fromto
  | SensorContact
  | EPotential
  | EKinetic
  | Clock
  | Tactile
  | SensorUser
  | SensorPlugin

union EqualityAny =
    Connect
  | Weld
  | EqualityJoint
  | EqualityTendon
  | EqualityFlex
  | Flexvert
  | Flexstrain

union TendonAny =
    Spatial
  | Fixed

union PathItemAny =
    SpatialSite
  | SpatialGeom
  | Pulley

# --- Elements -------------------------------------------------------------

element Model (xml="mujoco") {
  model : string
  children compilers : Compiler *
  children options : Option *
  children sizes : Size *
  children visuals : Visual *
  children statistics : Statistic *
  children defaults : Default *
  children extensions : Extension *
  children customs : Custom *
  children assets : Asset *
  children worldbody : Body *
  children deformables : Deformable *
  children contacts : Contact *
  children equalitys : Equality *
  children tendons : Tendon *
  children actuators : Actuator *
  children sensors : Sensor *
  children keyframes : Keyframe *
}

element Compiler {
  autolimits        : bool   # infer "limited" attribute based on range
  boundmass         : double   # enforce minimum body mass
  boundinertia      : double   # enforce minimum body diagonal inertia
  settotalmass      : double   # rescale masses and inertias; <=0: ignore
  balanceinertia    : bool   # automatically impose A + B >= C rule
  strippath         : bool
  coordinate        : Coordinate
  angle             : AngleUnit
  fitaabb           : bool   # meshfit to aabb instead of inertia box
  eulerseq          : string   # sequence for euler rotations
  meshdir           : string   # mesh and hfield directory
  texturedir        : string   # texture directory
  discardvisual     : bool   # discard visual geoms in parser
  usethread         : bool   # use multiple threads to speed up compiler
  fusestatic        : bool   # fuse static bodies with parent
  inertiafromgeom   : InertiaFromGeom   # use geom inertias (mjtInertiaFromGeom)
  inertiagrouprange : int32[2]   # range of geom groups used to compute inertia
  saveinertial      : bool   # save explicit inertial clause for all bodies to XML
  assetdir          : string
  alignfree         : bool   # align free joints with inertial frame
  children lengthRanges : LengthRange ?
}

element LengthRange {
  mode        : LRMode
  useexisting : bool
  uselimit    : bool
  accel       : double
  maxforce    : double
  timeconst   : double
  timestep    : double
  inttotal    : double
  interval    : double
  tolrange    : double
}

element Option {
  timestep             : double
  impratio             : double
  tolerance            : double
  ls_tolerance         : double
  noslip_tolerance     : double
  ccd_tolerance        : double
  sleep_tolerance      : double
  gravity              : double[3]
  wind                 : double[3]
  magnetic             : double[3]
  density              : double
  viscosity            : double
  o_margin             : double
  o_solref             : double[2]
  o_solimp             : double[5]
  o_friction           : double[5]
  integrator           : Integrator
  cone                 : Cone
  jacobian             : JacobianType
  solver               : SolverType
  iterations           : int32
  ls_iterations        : int32
  noslip_iterations    : int32
  ccd_iterations       : int32
  sdf_iterations       : int32
  sdf_initpoints       : int32
  actuatorgroupdisable : int32[]
  children flags : Flag ?
}

element Flag {
  constraint   : bool
  equality     : bool
  frictionloss : bool
  limit        : bool
  contact      : bool
  spring       : bool
  damper       : bool
  gravity      : bool
  clampctrl    : bool
  warmstart    : bool
  filterparent : bool
  actuation    : bool
  refsafe      : bool
  sensor       : bool
  midphase     : bool
  eulerdamp    : bool
  autoreset    : bool
  nativeccd    : bool
  island       : bool
  override     : bool
  energy       : bool
  fwdinv       : bool
  invdiscrete  : bool
  multiccd     : bool
  sleep        : bool
  diagexact    : bool
}

element Size {
  memory         : string
  njmax          : int32
  nconmax        : int32
  nstack         : int32
  nuserdata      : int32
  nkey           : int32
  nuser_body     : int32
  nuser_jnt      : int32
  nuser_geom     : int32
  nuser_site     : int32
  nuser_cam      : int32
  nuser_tendon   : int32
  nuser_actuator : int32
  nuser_sensor   : int32
}

element Visual {
  children visualGlobals : VisualGlobal ?
  children visualQualitys : VisualQuality ?
  children visualHeadlights : VisualHeadlight ?
  children visualMaps : VisualMap ?
  children visualScales : VisualScale ?
  children visualRgbas : VisualRgba ?
}

element VisualGlobal (xml="global") {
  cameraid         : int32
  orthographic     : bool
  fovy             : double
  ipd              : double
  azimuth          : double
  elevation        : double
  linewidth        : double
  glow             : double
  offwidth         : int32
  offheight        : int32
  realtime         : double
  ellipsoidinertia : bool
  bvactive         : bool
}

element VisualQuality (xml="quality") {
  shadowsize : int32
  offsamples : int32
  numslices  : int32
  numstacks  : int32
  numquads   : int32
}

element VisualHeadlight (xml="headlight") {
  ambient  : float[3]
  diffuse  : float[3]
  specular : float[3]
  active   : int32
}

element VisualMap (xml="map") {
  stiffness      : double
  stiffnessrot   : double
  force          : double
  torque         : double
  alpha          : double
  fogstart       : double
  fogend         : double
  znear          : double
  zfar           : double
  haze           : double
  shadowclip     : double
  shadowscale    : double
  actuatortendon : double
}

element VisualScale (xml="scale") {
  forcewidth     : double
  contactwidth   : double
  contactheight  : double
  connect        : double
  com            : double
  camera         : double
  light          : double
  selectpoint    : double
  jointlength    : double
  jointwidth     : double
  actuatorlength : double
  actuatorwidth  : double
  framelength    : double
  framewidth     : double
  constraint     : double
  slidercrank    : double
  frustum        : double
}

element VisualRgba (xml="rgba") {
  fog              : float[4]
  haze             : float[4]
  force            : float[4]
  inertia          : float[4]
  joint            : float[4]
  actuator         : float[4]
  actuatornegative : float[4]
  actuatorpositive : float[4]
  com              : float[4]
  camera           : float[4]
  light            : float[4]
  selectpoint      : float[4]
  connect          : float[4]
  contactpoint     : float[4]
  contactforce     : float[4]
  contactfriction  : float[4]
  contacttorque    : float[4]
  contactgap       : float[4]
  rangefinder      : float[4]
  constraint       : float[4]
  slidercrank      : float[4]
  crankbroken      : float[4]
  frustum          : float[4]
  bv               : float[4]
  bvactive         : float[4]
}

element Statistic {
  meaninertia : double
  meanmass    : double
  meansize    : double
  extent      : double
  center      : double[3]
}

element Default {
  dclass : string (xml="class")   # name of this default class
  children mesh : Mesh ?
  children material : Material ?
  children joint : Joint ?
  children geom : Geom ?
  children site : Site ?
  children camera : Camera ?
  children light : Light ?
  children pair : Pair ?
  children equality : EqualityDefault ?
  children tendon : TendonDefault ?
  children general : ActuatorGeneral ?
  children motor : Motor ?
  children position : Position ?
  children velocity : Velocity ?
  children intvelocity : IntVelocity ?
  children damper : Damper ?
  children cylinder : Cylinder ?
  children muscle : Muscle ?
  children adhesion : Adhesion ?
  children dcmotor : DcMotor ?
  children subclasses : Default *
}

element EqualityDefault (xml="equality") {
  active : bool = true   # is equality initially active
  solref : double[0..2]   # solver reference
  solimp : double[0..5]   # solver impedance
}

element TendonDefault (xml="tendon") {
  group          : int32   # group
  limited        : TriState   # does tendon have limits (mjtLimited)
  range          : double[2]   # length limits
  solreflimit    : double[0..2]   # solver reference: tendon limits
  solimplimit    : double[0..5]   # solver impedance: tendon limits
  solreffriction : double[0..2]   # solver reference: tendon friction
  solimpfriction : double[0..5]   # solver impedance: tendon friction
  frictionloss   : double   # friction loss
  springlength   : double[2] = {-1, -1}   # spring resting length; {-1, -1}: use qpos_spring
  width          : double = 0.003   # width for rendering
  material       : ref<Material>   # name of material for rendering
  margin         : double   # margin value for tendon limit detection
  stiffness      : double[3]   # stiffness coefficients
  damping        : double[3]   # damping coefficients
  rgba           : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  user           : double[]   # user data
}

element Extension {
  children pluginDefs : PluginDef *
}

element PluginDef (xml="plugin") {
  plugin : string
  children pluginInstances : PluginInstance *
}

element PluginInstance (xml="instance") {
  name : string   # element name
  children config : Config *
}

element Config {
  key   : string
  value : string
}

element Custom {
  children numerics : Numeric *
  children texts : Text *
  children tuples : Tuple *
}

element Numeric {
  name : string   # element name
  size : int32   # array size, can be bigger than data size
  data : double[]   # initialization data
}

element Text {
  name : string   # element name
  data : string   # text string
}

element Tuple {
  name : string   # element name
  children tupleElements : TupleElement *
}

element TupleElement (xml="element") {
  objtype : string
  objname : string
  prm     : double[]
}

element Asset {
  children meshs : Mesh *
  children hfields : Hfield *
  children skins : Skin *
  children textures : Texture *
  children materials : Material *
  children modelAssets : ModelAsset *
}

element Mesh {
  name         : string   # element name
  dclass       : ref<Default> (xml="class")   # default class
  content_type : string   # content type of file
  file         : string   # mesh file
  vertex       : double[]
  normal       : double[]
  texcoord     : float[]
  face         : int32[]
  refpos       : double[3]   # reference position
  refquat      : double[4]   # reference orientation
  scale        : double[3] = {1, 1, 1}   # rescale mesh
  smoothnormal : bool   # do not exclude large-angle faces from normals
  maxhullvert  : int32   # maximum vertex count for the convex hull
  inertia      : MeshInertia = legacy   # inertia type (convex, legacy, exact, shell)
  builtin      : MeshBuiltin
  params       : double[]
  material     : ref<Material>   # name of material
  children plugin : PluginRef *
}

element PluginRef (xml="plugin") {
  plugin   : string   # plugin name
  instance : ref<PluginInstance>   # plugin instance name
  children config : Config *
}

element Hfield {
  name         : string   # element name
  content_type : string   # content type of file
  file         : string   # file: (nrow, ncol, [elevation data])
  nrow         : int32   # number of rows
  ncol         : int32   # number of columns
  size         : double[4]   # hfield size (ignore referencing geom size)
  elevation    : double[]
}

element Skin {
  name     : string   # element name
  file     : string   # skin file
  material : ref<Material>   # name of material used for rendering
  rgba     : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  inflate  : float   # inflate in normal direction
  vertex   : float[]   # vertex positions
  texcoord : float[]   # texture coordinates
  face     : int32[]   # faces
  group    : int32   # group for visualization
  children bones : SkinBone *
}

element SkinBone (xml="bone") {
  body       : string
  bindpos    : double[3]
  bindquat   : double[4]
  vertid     : int32[]
  vertweight : float[]
}

element Texture {
  name         : string   # element name
  type         : TextureType = cube   # texture type
  colorspace   : ColorSpace = auto   # colorspace
  content_type : string   # content type of file
  gridsize     : int32[2] = {1, 1}   # size of grid for composite file; (1,1)-repeat
  gridlayout   : string   # row-major: L,R,F,B,U,D for faces; . for unused
  fileright    : string   # image file for one cube face
  fileleft     : string   # image file for one cube face
  fileup       : string   # image file for one cube face
  filedown     : string   # image file for one cube face
  filefront    : string   # image file for one cube face
  fileback     : string   # image file for one cube face
  rgb1         : double[3] = {0.8, 0.8, 0.8}   # first color for builtin
  rgb2         : double[3] = {0.5, 0.5, 0.5}   # second color for builtin
  mark         : TextureMark   # mark type (mjtMark)
  markrgb      : double[3]   # mark color
  random       : double = 0.01   # probability of random dots
  width        : int32   # width in pixels
  height       : int32   # height in pixels (square for cube and skybox)
  hflip        : bool   # horizontal flip
  vflip        : bool   # vertical flip
  nchannel     : int32 = 3   # number of channels
  source       : variant TextureSource   # builtin generator or image file
}

element Material {
  name        : string   # element name
  dclass      : ref<Default> (xml="class")   # default class
  texture     : ref<Texture>
  texrepeat   : float[2] = {1, 1}   # texture repetition for 2D mapping
  texuniform  : bool   # make texture cube uniform
  emission    : float   # emission
  specular    : float = 0.5   # specular
  shininess   : float = 0.5   # shininess
  reflectance : float   # reflectance
  metallic    : float   # metallic
  roughness   : float   # roughness
  rgba        : float[4] = {1, 1, 1, 1}   # rgba
  children layers : MaterialLayer *
}

element MaterialLayer (xml="layer") {
  texture : ref<Texture>
  role    : TexRole
}

element ModelAsset (xml="model") {
  name         : string   # element name
  file         : string
  content_type : string
}

element Body {
  use Posed
  name       : string   # element name
  childclass : ref<Default>   # default class applied to descendants
  mocap      : bool   # is this a mocap body
  gravcomp   : double   # gravity compensation
  sleep      : BodySleep   # sleep policy
  user       : double[]   # user data
  children inertial : Inertial ?
  children joints : Joint *
  children freejoint : FreeJoint *
  children geoms : Geom *
  children attach : Attach *
  children sites : Site *
  children cameras : Camera *
  children lights : Light *
  children plugin : PluginRef *
  children composites : Composite *
  children flexcomps : Flexcomp *
  children frames : Frame *
}

element Inertial {
  pos     : double[3]   # frame position
  mass    : double   # mass
  iorient : variant Orientation   # inertial frame orientation
  inertia : variant InertiaSpec   # diagonal or full inertia
}

element Joint {
  name               : string   # element name
  dclass             : ref<Default> (xml="class")   # default class
  type               : JointType = hinge   # joint type
  group              : int32   # group
  pos                : double[3]   # anchor position
  axis               : double[3] = {0, 0, 1}   # joint axis
  springdamper       : double[2]   # timeconst, dampratio
  limited            : TriState   # does joint have limits (mjtLimited)
  actuatorfrclimited : TriState   # are actuator forces on joint limited (mjtLimited)
  solreflimit        : double[0..2]   # solver reference: joint limits
  solimplimit        : double[0..5]   # solver impedance: joint limits
  solreffriction     : double[0..2]   # solver reference: dof friction
  solimpfriction     : double[0..5]   # solver impedance: dof friction
  stiffness          : double[3]   # stiffness coefficients
  range              : double[2] (unit=angle)   # joint limits
  actuatorfrcrange   : double[2]   # actuator force limits
  actuatorgravcomp   : bool   # is gravcomp force applied via actuators
  margin             : double   # margin value for joint limit detection
  ref                : double (unit=angle)   # value at reference configuration: qpos0
  springref          : double (unit=angle)   # spring reference value: qpos_spring
  armature           : double   # armature inertia (mass for slider)
  damping            : double[3]   # damping coefficients
  frictionloss       : double   # friction loss
  user               : double[]   # user data
}

element FreeJoint {
  name  : string   # element name
  group : int32   # group
  align : int32   # align free joint with body com (mjtAlignFree)
}

element Geom {
  use Posed
  name         : string   # element name
  dclass       : ref<Default> (xml="class")   # default class
  type         : GeomType = sphere   # geom type
  contype      : int32 = 1   # contact type
  conaffinity  : int32 = 1   # contact affinity
  condim       : int32 = 3   # contact dimensionality
  group        : int32   # group
  priority     : int32   # contact priority
  size         : double[0..3]   # type-specific size
  material     : ref<Material>   # name of material
  friction     : double[1..3] = {1, 0.005, 0.0001}   # one-sided friction coefficients: slide, roll, spin
  mass         : double   # used to compute density
  density      : double = 1000   # used to compute mass and inertia from volume or surface
  shellinertia : bool   # use shell (surface) instead of volume inertia
  solmix       : double = 1   # solver mixing for contact pairs
  solref       : double[0..2]   # solver reference
  solimp       : double[0..5]   # solver impedance
  margin       : double   # margin for contact detection
  gap          : double   # additional contact detection buffer
  hfield       : ref<Hfield>   # heightfield attached to geom
  mesh         : ref<Mesh>   # mesh attached to geom
  fitscale     : double = 1   # scale mesh uniformly
  rgba         : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  fluidshape   : FluidShape
  fluidcoef    : double[0..5] = {0.5, 0.25, 1.5, 1, 1}   # ellipsoid-fluid interaction coefs
  user         : double[]   # user data
  shape        : variant GeomShape   # explicit size or fromto endpoints
  children plugin : PluginRef *
}

element Attach {
  model  : ref<ModelAsset>
  body   : string
  prefix : string
}

element Site {
  use Posed
  name     : string   # element name
  dclass   : ref<Default> (xml="class")   # default class
  type     : GeomType = sphere   # geom type
  group    : int32   # group
  material : ref<Material>   # name of material
  size     : double[0..3] = {0.005, 0.005, 0.005}   # geom size
  rgba     : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  user     : double[]   # user data
  shape    : variant GeomShape   # explicit size or fromto endpoints
}

element Camera {
  use Posed
  name           : string   # element name
  dclass         : ref<Default> (xml="class")   # default class
  projection     : CameraProjection
  ipd            : double = 0.068   # inter-pupillary distance
  resolution     : int32[2] = {1, 1}   # resolution (pixel)
  output         : CameraOutput = rgb   # bit flags for output type
  mode           : CamLightMode = fixed   # tracking mode
  target         : ref<Body>   # target body for tracking/targeting
  focalpixel     : float[2]   # focal length (pixel)
  principal      : float[2]   # principal point (length)
  principalpixel : float[2]   # principal point (pixel)
  sensorsize     : float[2]   # sensor size (length)
  user           : double[]   # user data
  intrinsics     : variant CameraIntrinsics   # field of view or focal length
}

element Light {
  name        : string   # element name
  dclass      : ref<Default> (xml="class")   # default class
  directional : bool
  type        : LightType   # type of light
  castshadow  : bool = true   # does light cast shadows
  active      : bool = true   # is light active
  pos         : double[3]   # position
  dir         : double[3] = {0, 0, -1}   # direction
  bulbradius  : float = 0.02   # bulb radius, for soft shadows
  intensity   : float = 0   # intensity, in candelas
  range       : float = 10   # range of effectiveness
  attenuation : float[3]   # OpenGL attenuation (quadratic model)
  cutoff      : float = 45   # OpenGL cutoff
  exponent    : float = 10   # OpenGL exponent
  ambient     : float[3]   # ambient color
  diffuse     : float[3] = {0.7, 0.7, 0.7}   # diffuse color
  specular    : float[3] = {0.3, 0.3, 0.3}   # specular color
  mode        : CamLightMode = fixed   # tracking mode
  target      : ref<Body>   # target body for targeting
  texture     : ref<Texture>   # texture name for image lights
}

element Composite {
  prefix  : string
  type    : CompositeType
  count   : int32
  offset  : double[3]
  vertex  : double[]   # vertex positions
  initial : string
  curve   : string
  size    : double[3]   # vertex bounding box half sizes in qpos0
  quat    : double[4]
  children compositeJoints : CompositeJoint *
  children compositeSkins : CompositeSkin ?
  children compositeGeoms : CompositeGeom ?
  children compositeSites : CompositeSite ?
  children plugin : PluginRef *
}

element CompositeJoint (xml="joint") {
  kind           : string
  group          : int32
  stiffness      : double
  damping        : double
  armature       : double
  solreffix      : double[0..2]
  solimpfix      : double[0..5]
  type           : JointType
  axis           : double[3]
  limited        : TriState
  range          : double[2]
  margin         : double
  solreflimit    : double[0..2]
  solimplimit    : double[0..5]
  frictionloss   : double
  solreffriction : double[0..2]
  solimpfriction : double[0..5]
}

element CompositeSkin (xml="skin") {
  texcoord : float[]   # texture coordinates
  material : string   # name of material used for rendering
  group    : int32   # group for visualization
  rgba     : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  inflate  : float   # inflate in normal direction
  subgrid  : int32
}

element CompositeGeom (xml="geom") {
  type        : GeomType = sphere   # geom type
  contype     : int32 = 1   # contact type
  conaffinity : int32 = 1   # contact affinity
  condim      : int32 = 3   # contact dimensionality
  group       : int32   # group
  priority    : int32   # contact priority
  size        : double[0..3]   # type-specific size
  material    : string   # name of material
  rgba        : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  friction    : double[1..3] = {1, 0.005, 0.0001}   # one-sided friction coefficients: slide, roll, spin
  mass        : double   # used to compute density
  density     : double = 1000   # used to compute mass and inertia from volume or surface
  solmix      : double = 1   # solver mixing for contact pairs
  solref      : double[0..2]   # solver reference
  solimp      : double[0..5]   # solver impedance
  margin      : double   # margin for contact detection
  gap         : double   # additional contact detection buffer
}

element CompositeSite (xml="site") {
  group    : int32   # group
  size     : double[0..3] = {0.005, 0.005, 0.005}   # geom size
  material : string   # name of material
  rgba     : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
}

element Flexcomp {
  name       : string   # element name
  type       : FlexcompType
  group      : int32   # group for visualization
  dim        : int32 = 2   # element dimensionality
  dof        : FlexDof
  count      : int32
  cellcount  : int32[3] = {1, 1, 1}   # grid cell count for finite cell method
  spacing    : double[3]
  radius     : double = 0.005   # radius around primitive element
  rigid      : bool
  mass       : double
  inertiabox : double
  scale      : double[3]
  file       : string
  point      : double[]
  element    : double   # element type
  texcoord   : float[]   # vertex texture coordinates
  material   : string   # name of material used for rendering
  rgba       : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  flatskin   : bool   # render flex skin with flat shading
  pos        : double[3]
  quat       : double[4]
  axisangle  : double[4]
  xyaxes     : double[6]
  zaxis      : double[3]
  euler      : double[3]
  origin     : double[3]
  children flexcompEdges : FlexcompEdge ?
  children flexElasticitys : FlexElasticity ?
  children flexContacts : FlexContact ?
  children flexcompPins : FlexcompPin *
  children plugin : PluginRef *
}

element FlexcompEdge (xml="edge") {
  equality  : FlexEquality
  solref    : double[0..2]
  solimp    : double[0..5]
  stiffness : double
  damping   : double
}

element FlexElasticity (xml="elasticity") {
  young     : double   # Young's modulus
  poisson   : double   # Poisson's ratio
  damping   : double   # Rayleigh's damping
  thickness : double   # thickness (2D only)
  elastic2d : Elastic2D   # 2D passive forces; 0: none, 1: bending, 2: stretching, 3: both
}

element FlexContact (xml="contact") {
  contype      : int32 = 1   # contact type
  conaffinity  : int32 = 1   # contact affinity
  condim       : int32 = 3   # contact dimensionality
  priority     : int32   # contact priority
  friction     : double[1..3] = {1, 0.005, 0.0001}   # one-sided friction coefficients: slide, roll, spin
  solmix       : double = 1   # solver mixing for contact pairs
  solref       : double[0..2]   # solver reference
  solimp       : double[0..5]   # solver impedance
  margin       : double   # margin for contact detection
  gap          : double   # additional contact detection buffer
  internal     : bool = false   # enable internal collisions
  selfcollide  : FlexSelfCollide = auto   # mode for flex self collision
  activelayers : int32 = 1   # number of active element layers in 3D
  passive      : int32   # mode for passive collisions
}

element FlexcompPin (xml="pin") {
  id        : int32[]
  range     : double[2]
  grid      : int32[]
  gridrange : int32[]
}

element Deformable {
  children flexs : Flex *
  children skins : Skin *
}

element Flex {
  name         : string   # element name
  group        : int32   # group for visualization
  dim          : int32 = 2   # element dimensionality
  radius       : double = 0.005   # radius around primitive element
  material     : string   # name of material used for rendering
  rgba         : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  flatskin     : bool   # render flex skin with flat shading
  body         : string
  vertex       : double[]   # vertex positions
  element      : double   # element type
  texcoord     : float[]   # vertex texture coordinates
  elemtexcoord : int32[]   # element texture coordinates
  node         : double[]   # node positions
  cellcount    : int32[3] = {1, 1, 1}   # grid cell count for finite cell method
  dof          : FlexDof
  children flexContacts : FlexContact ?
  children flexEdges : FlexEdge ?
  children flexElasticitys : FlexElasticity ?
}

element FlexEdge (xml="edge") {
  stiffness : double
  damping   : double
}

element Contact {
  children pairs : Pair *
  children excludes : Exclude *
}

element Pair {
  name           : string   # element name
  dclass         : ref<Default> (xml="class")   # default class
  geom1          : ref<Geom>   # name of geom 1
  geom2          : ref<Geom>   # name of geom 2
  condim         : int32 = 3   # contact dimensionality
  friction       : double[5] = {1, 1, 0.005, 0.0001, 0.0001}   # full contact friction
  solref         : double[0..2]   # solver reference, normal direction
  solreffriction : double[0..2]
  solimp         : double[0..5]   # solver impedance
  gap            : double   # additional contact detection buffer
  margin         : double   # margin for contact detection
}

element Exclude {
  name  : string   # element name
  body1 : ref<Body>   # name of geom 1
  body2 : ref<Body>   # name of geom 2
}

element Equality {
  children equalities : EqualityAny *
}

element Connect {
  name   : string   # element name
  dclass : ref<Default> (xml="class")   # default class
  body1  : ref<Body>
  body2  : ref<Body>
  anchor : double[3]
  site1  : ref<Site>
  site2  : ref<Site>
  active : bool = true   # is equality initially active
  solref : double[0..2]   # solver reference
  solimp : double[0..5]   # solver impedance
}

element Weld {
  name        : string   # element name
  dclass      : ref<Default> (xml="class")   # default class
  body1       : ref<Body>
  body2       : ref<Body>
  relpose     : double[7]
  anchor      : double[3]
  site1       : ref<Site>
  site2       : ref<Site>
  active      : bool = true   # is equality initially active
  solref      : double[0..2]   # solver reference
  solimp      : double[0..5]   # solver impedance
  torquescale : double
}

element EqualityJoint (xml="joint") {
  name     : string   # element name
  dclass   : ref<Default> (xml="class")   # default class
  joint1   : ref<Joint>
  joint2   : ref<Joint>
  polycoef : double[]
  active   : bool = true   # is equality initially active
  solref   : double[0..2]   # solver reference
  solimp   : double[0..5]   # solver impedance
}

element EqualityTendon (xml="tendon") {
  name     : string   # element name
  dclass   : ref<Default> (xml="class")   # default class
  tendon1  : ref<TendonAny>
  tendon2  : ref<TendonAny>
  polycoef : double[]
  active   : bool = true   # is equality initially active
  solref   : double[0..2]   # solver reference
  solimp   : double[0..5]   # solver impedance
}

element EqualityFlex (xml="flex") {
  name   : string   # element name
  dclass : ref<Default> (xml="class")   # default class
  flex   : ref<Flex>
  active : bool = true   # is equality initially active
  solref : double[0..2]   # solver reference
  solimp : double[0..5]   # solver impedance
}

element Flexvert {
  name   : string   # element name
  dclass : ref<Default> (xml="class")   # default class
  flex   : ref<Flex>
  active : bool = true   # is equality initially active
  solref : double[0..2]   # solver reference
  solimp : double[0..5]   # solver impedance
}

element Flexstrain {
  name   : string   # element name
  dclass : ref<Default> (xml="class")   # default class
  flex   : ref<Flex>
  cell   : int32
  active : bool = true   # is equality initially active
  solref : double[0..2]   # solver reference
  solimp : double[0..5]   # solver impedance
}

element Tendon {
  children tendons : TendonAny *
}

element Spatial {
  name               : string   # element name
  dclass             : ref<Default> (xml="class")   # default class
  group              : int32   # group
  limited            : TriState   # does tendon have limits (mjtLimited)
  actuatorfrclimited : TriState   # does tendon have actuator force limits
  range              : double[2]   # length limits
  actuatorfrcrange   : double[2]   # actuator force limits
  solreflimit        : double[0..2]   # solver reference: tendon limits
  solimplimit        : double[0..5]   # solver impedance: tendon limits
  solreffriction     : double[0..2]   # solver reference: tendon friction
  solimpfriction     : double[0..5]   # solver impedance: tendon friction
  frictionloss       : double   # friction loss
  springlength       : double[2] = {-1, -1}   # spring resting length; {-1, -1}: use qpos_spring
  width              : double = 0.003   # width for rendering
  material           : ref<Material>   # name of material for rendering
  margin             : double   # margin value for tendon limit detection
  stiffness          : double[3]   # stiffness coefficients
  damping            : double[3]   # damping coefficients
  armature           : double   # inertia associated with tendon velocity
  rgba               : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  user               : double[]   # user data
  children path : PathItemAny *
}

element SpatialSite (xml="site") {
  site : ref<Site>
}

element SpatialGeom (xml="geom") {
  geom     : ref<Geom>
  sidesite : ref<Site>
}

element Pulley {
  divisor : double
}

element Fixed {
  name               : string   # element name
  dclass             : ref<Default> (xml="class")   # default class
  group              : int32   # group
  limited            : TriState   # does tendon have limits (mjtLimited)
  actuatorfrclimited : TriState   # does tendon have actuator force limits
  range              : double[2]   # length limits
  actuatorfrcrange   : double[2]   # actuator force limits
  solreflimit        : double[0..2]   # solver reference: tendon limits
  solimplimit        : double[0..5]   # solver impedance: tendon limits
  solreffriction     : double[0..2]   # solver reference: tendon friction
  solimpfriction     : double[0..5]   # solver impedance: tendon friction
  frictionloss       : double   # friction loss
  springlength       : double[2] = {-1, -1}   # spring resting length; {-1, -1}: use qpos_spring
  margin             : double   # margin value for tendon limit detection
  stiffness          : double[3]   # stiffness coefficients
  damping            : double[3]   # damping coefficients
  armature           : double   # inertia associated with tendon velocity
  user               : double[]   # user data
  children fixedJoints : FixedJoint *
}

element FixedJoint (xml="joint") {
  joint : ref<Joint>
  coef  : double
}

element Actuator {
  children actuators : ActuatorAny *
}

element ActuatorGeneral (xml="general") {
  name          : string   # element name
  dclass        : ref<Default> (xml="class")   # default class
  group         : int32   # group
  nsample       : int32   # number of samples in history buffer
  interp        : InterpType   # interpolation order (0=ZOH, 1=linear, 2=cubic)
  delay         : double   # delay time in seconds; 0: no delay
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  actlimited    : TriState   # are activation limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  actrange      : double[2]   # activation range
  lengthrange   : double[2]   # transmission length range
  gear          : double[0..6] = {1}   # length and transmitted force scaling
  damping       : double[3]   # damping coefficients
  armature      : double   # armature inertia
  cranklength   : double   # crank length, for slider-crank
  user          : double[]   # user data
  joint         : ref<Joint>
  jointinparent : ref<Joint>
  tendon        : ref<TendonAny>
  slidersite    : ref<Site>   # site defining cylinder, for slider-crank
  cranksite     : ref<Site>
  site          : ref<Site>
  refsite       : ref<Site>   # reference site, for site transmission
  body          : ref<Body>
  actdim        : int32   # number of activation variables
  dyntype       : DynType = none   # dynamics type
  gaintype      : GainType = fixed   # gain type
  biastype      : BiasType = none   # bias type
  dynprm        : double[10]   # dynamics parameters
  gainprm       : double[10]   # gain parameters
  biasprm       : double[10]   # bias parameters
  actearly      : bool   # apply next activations to qfrc
}

element Motor {
  name          : string   # element name
  dclass        : ref<Default> (xml="class")   # default class
  group         : int32   # group
  nsample       : int32   # number of samples in history buffer
  interp        : InterpType   # interpolation order (0=ZOH, 1=linear, 2=cubic)
  delay         : double   # delay time in seconds; 0: no delay
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  lengthrange   : double[2]   # transmission length range
  gear          : double[0..6] = {1}   # length and transmitted force scaling
  damping       : double[3]   # damping coefficients
  armature      : double   # armature inertia
  cranklength   : double   # crank length, for slider-crank
  user          : double[]   # user data
  joint         : ref<Joint>
  jointinparent : ref<Joint>
  tendon        : ref<TendonAny>
  slidersite    : ref<Site>   # site defining cylinder, for slider-crank
  cranksite     : ref<Site>
  site          : ref<Site>
  refsite       : ref<Site>   # reference site, for site transmission
}

element Position {
  name          : string   # element name
  dclass        : ref<Default> (xml="class")   # default class
  group         : int32   # group
  nsample       : int32   # number of samples in history buffer
  interp        : InterpType   # interpolation order (0=ZOH, 1=linear, 2=cubic)
  delay         : double   # delay time in seconds; 0: no delay
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  inheritrange  : double   # automatic range setting for position and intvelocity
  forcerange    : double[2]   # force range
  lengthrange   : double[2]   # transmission length range
  gear          : double[0..6] = {1}   # length and transmitted force scaling
  damping       : double[3]   # damping coefficients
  armature      : double   # armature inertia
  cranklength   : double   # crank length, for slider-crank
  user          : double[]   # user data
  joint         : ref<Joint>
  jointinparent : ref<Joint>
  tendon        : ref<TendonAny>
  slidersite    : ref<Site>   # site defining cylinder, for slider-crank
  cranksite     : ref<Site>
  site          : ref<Site>
  refsite       : ref<Site>   # reference site, for site transmission
  kp            : double   # position feedback gain
  kv            : double   # velocity feedback gain
  dampratio     : double   # damping ratio, in units of critical damping
  timeconst     : double   # time constant of the activation dynamics
}

element Velocity {
  name          : string   # element name
  dclass        : ref<Default> (xml="class")   # default class
  group         : int32   # group
  nsample       : int32   # number of samples in history buffer
  interp        : InterpType   # interpolation order (0=ZOH, 1=linear, 2=cubic)
  delay         : double   # delay time in seconds; 0: no delay
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  lengthrange   : double[2]   # transmission length range
  gear          : double[0..6] = {1}   # length and transmitted force scaling
  damping       : double[3]   # damping coefficients
  armature      : double   # armature inertia
  cranklength   : double   # crank length, for slider-crank
  user          : double[]   # user data
  joint         : ref<Joint>
  jointinparent : ref<Joint>
  tendon        : ref<TendonAny>
  slidersite    : ref<Site>   # site defining cylinder, for slider-crank
  cranksite     : ref<Site>
  site          : ref<Site>
  refsite       : ref<Site>   # reference site, for site transmission
  kv            : double   # velocity feedback gain
}

element IntVelocity {
  name          : string   # element name
  dclass        : ref<Default> (xml="class")   # default class
  group         : int32   # group
  nsample       : int32   # number of samples in history buffer
  interp        : InterpType   # interpolation order (0=ZOH, 1=linear, 2=cubic)
  delay         : double   # delay time in seconds; 0: no delay
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  actrange      : double[2]   # activation range
  inheritrange  : double   # automatic range setting for position and intvelocity
  lengthrange   : double[2]   # transmission length range
  gear          : double[0..6] = {1}   # length and transmitted force scaling
  damping       : double[3]   # damping coefficients
  armature      : double   # armature inertia
  cranklength   : double   # crank length, for slider-crank
  user          : double[]   # user data
  joint         : ref<Joint>
  jointinparent : ref<Joint>
  tendon        : ref<TendonAny>
  slidersite    : ref<Site>   # site defining cylinder, for slider-crank
  cranksite     : ref<Site>
  site          : ref<Site>
  refsite       : ref<Site>   # reference site, for site transmission
  kp            : double   # position feedback gain
  kv            : double   # velocity feedback gain
  dampratio     : double   # damping ratio, in units of critical damping
}

element Damper {
  name          : string   # element name
  dclass        : ref<Default> (xml="class")   # default class
  group         : int32   # group
  nsample       : int32   # number of samples in history buffer
  interp        : InterpType   # interpolation order (0=ZOH, 1=linear, 2=cubic)
  delay         : double   # delay time in seconds; 0: no delay
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  lengthrange   : double[2]   # transmission length range
  gear          : double[0..6] = {1}   # length and transmitted force scaling
  damping       : double[3]   # damping coefficients
  armature      : double   # armature inertia
  cranklength   : double   # crank length, for slider-crank
  user          : double[]   # user data
  joint         : ref<Joint>
  jointinparent : ref<Joint>
  tendon        : ref<TendonAny>
  slidersite    : ref<Site>   # site defining cylinder, for slider-crank
  cranksite     : ref<Site>
  site          : ref<Site>
  refsite       : ref<Site>   # reference site, for site transmission
  kv            : double   # velocity feedback gain
}

element Cylinder {
  name          : string   # element name
  dclass        : ref<Default> (xml="class")   # default class
  group         : int32   # group
  nsample       : int32   # number of samples in history buffer
  interp        : InterpType   # interpolation order (0=ZOH, 1=linear, 2=cubic)
  delay         : double   # delay time in seconds; 0: no delay
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  lengthrange   : double[2]   # transmission length range
  gear          : double[0..6] = {1}   # length and transmitted force scaling
  damping       : double[3]   # damping coefficients
  armature      : double   # armature inertia
  cranklength   : double   # crank length, for slider-crank
  user          : double[]   # user data
  joint         : ref<Joint>
  jointinparent : ref<Joint>
  tendon        : ref<TendonAny>
  slidersite    : ref<Site>   # site defining cylinder, for slider-crank
  cranksite     : ref<Site>
  site          : ref<Site>
  refsite       : ref<Site>   # reference site, for site transmission
  timeconst     : double   # time constant of the activation dynamics
  area          : double   # cylinder area (alternative to diameter)
  diameter      : double   # cylinder diameter (alternative to area)
  bias          : double[3]   # cylinder bias parameters
}

element Muscle {
  name          : string   # element name
  dclass        : ref<Default> (xml="class")   # default class
  group         : int32   # group
  nsample       : int32   # number of samples in history buffer
  interp        : InterpType   # interpolation order (0=ZOH, 1=linear, 2=cubic)
  delay         : double   # delay time in seconds; 0: no delay
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  lengthrange   : double[2]   # transmission length range
  gear          : double[0..6] = {1}   # length and transmitted force scaling
  damping       : double[3]   # damping coefficients
  armature      : double   # armature inertia
  cranklength   : double   # crank length, for slider-crank
  user          : double[]   # user data
  joint         : ref<Joint>
  jointinparent : ref<Joint>
  tendon        : ref<TendonAny>
  slidersite    : ref<Site>   # site defining cylinder, for slider-crank
  cranksite     : ref<Site>
  timeconst     : double   # time constant of the activation dynamics
  tausmooth     : double
  range         : double[2]   # muscle operating length range
  force         : double   # peak active force (muscle); <0: automatic
  scale         : double   # muscle force = scale / acc0
  lmin          : double   # lower bound on muscle operating length
  lmax          : double   # upper bound on muscle operating length
  vmax          : double   # shortening velocity at which force drops to zero
  fpmax         : double   # peak passive force at length lmax
  fvmax         : double   # active force at saturating lengthening velocity
}

element Adhesion {
  name         : string   # element name
  dclass       : ref<Default> (xml="class")   # default class
  group        : int32   # group
  nsample      : int32   # number of samples in history buffer
  interp       : InterpType   # interpolation order (0=ZOH, 1=linear, 2=cubic)
  delay        : double   # delay time in seconds; 0: no delay
  forcelimited : TriState   # are force limits defined (mjtLimited)
  ctrlrange    : double[2]   # control range
  forcerange   : double[2]   # force range
  user         : double[]   # user data
  body         : ref<Body>
  gain         : double   # adhesion gain
}

element DcMotor {
  name          : string   # element name
  dclass        : ref<Default> (xml="class")   # default class
  group         : int32   # group
  nsample       : int32   # number of samples in history buffer
  interp        : InterpType   # interpolation order (0=ZOH, 1=linear, 2=cubic)
  delay         : double   # delay time in seconds; 0: no delay
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  lengthrange   : double[2]   # transmission length range
  gear          : double[0..6] = {1}   # length and transmitted force scaling
  damping       : double[3]   # damping coefficients
  armature      : double   # armature inertia
  cranklength   : double   # crank length, for slider-crank
  user          : double[]   # user data
  joint         : ref<Joint>
  jointinparent : ref<Joint>
  tendon        : ref<TendonAny>
  slidersite    : ref<Site>   # site defining cylinder, for slider-crank
  cranksite     : ref<Site>
  site          : ref<Site>
  refsite       : ref<Site>   # reference site, for site transmission
  motorconst    : double   # motor torque constant
  resistance    : double   # armature resistance
  nominal       : double   # nominal supply voltage
  saturation    : double   # voltage saturation
  inductance    : double   # armature inductance
  cogging       : double   # cogging torque amplitude
  controller    : double[3]   # controller gains
  thermal       : double[2]   # thermal model parameters
  lugre         : double[5]   # LuGre friction parameters
  input         : DcMotorInput
}

element ActuatorPlugin (xml="plugin") {
  name          : string   # element name
  dclass        : ref<Default> (xml="class")   # default class
  plugin        : double   # actuator plugin
  instance      : ref<PluginInstance>
  group         : int32   # group
  nsample       : int32   # number of samples in history buffer
  interp        : InterpType   # interpolation order (0=ZOH, 1=linear, 2=cubic)
  delay         : double   # delay time in seconds; 0: no delay
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  actlimited    : TriState   # are activation limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  actrange      : double[2]   # activation range
  lengthrange   : double[2]   # transmission length range
  gear          : double[0..6] = {1}   # length and transmitted force scaling
  damping       : double[3]   # damping coefficients
  armature      : double   # armature inertia
  cranklength   : double   # crank length, for slider-crank
  joint         : ref<Joint>
  jointinparent : ref<Joint>
  site          : ref<Site>
  actdim        : int32   # number of activation variables
  dyntype       : DynType   # dynamics type
  dynprm        : double[10]   # dynamics parameters
  tendon        : ref<TendonAny>
  cranksite     : ref<Site>
  slidersite    : ref<Site>   # site defining cylinder, for slider-crank
  user          : double[]   # user data
  actearly      : bool   # apply next activations to qfrc
  children config : Config *
}

element Sensor {
  children sensors : SensorAny *
}

element Touch {
  name     : string   # element name
  site     : ref<Site>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Accelerometer {
  name     : string   # element name
  site     : ref<Site>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Velocimeter {
  name     : string   # element name
  site     : ref<Site>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Gyro {
  name     : string   # element name
  site     : ref<Site>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Force {
  name     : string   # element name
  site     : ref<Site>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Torque {
  name     : string   # element name
  site     : ref<Site>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Magnetometer {
  name     : string   # element name
  site     : ref<Site>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Camprojection {
  name     : string   # element name
  site     : ref<Site>
  camera   : ref<Camera>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Rangefinder {
  name     : string   # element name
  site     : ref<Site>
  camera   : ref<Camera>
  data     : RayData
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Jointpos {
  name     : string   # element name
  joint    : ref<Joint>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Jointvel {
  name     : string   # element name
  joint    : ref<Joint>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Tendonpos {
  name     : string   # element name
  tendon   : ref<TendonAny>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Tendonvel {
  name     : string   # element name
  tendon   : ref<TendonAny>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Actuatorpos {
  name     : string   # element name
  actuator : string
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Actuatorvel {
  name     : string   # element name
  actuator : string
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Actuatorfrc {
  name     : string   # element name
  actuator : string
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Jointactuatorfrc {
  name     : string   # element name
  joint    : ref<Joint>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Tendonactuatorfrc {
  name     : string   # element name
  tendon   : ref<TendonAny>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Ballquat {
  name     : string   # element name
  joint    : ref<Joint>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Ballangvel {
  name     : string   # element name
  joint    : ref<Joint>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Jointlimitpos {
  name     : string   # element name
  joint    : ref<Joint>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Jointlimitvel {
  name     : string   # element name
  joint    : ref<Joint>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Jointlimitfrc {
  name     : string   # element name
  joint    : ref<Joint>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Tendonlimitpos {
  name     : string   # element name
  tendon   : ref<TendonAny>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Tendonlimitvel {
  name     : string   # element name
  tendon   : ref<TendonAny>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Tendonlimitfrc {
  name     : string   # element name
  tendon   : ref<TendonAny>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Framepos {
  name     : string   # element name
  objtype  : string
  objname  : string
  reftype  : string
  refname  : string
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Framequat {
  name     : string   # element name
  objtype  : string
  objname  : string
  reftype  : string
  refname  : string
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Framexaxis {
  name     : string   # element name
  objtype  : string
  objname  : string
  reftype  : string
  refname  : string
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Frameyaxis {
  name     : string   # element name
  objtype  : string
  objname  : string
  reftype  : string
  refname  : string
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Framezaxis {
  name     : string   # element name
  objtype  : string
  objname  : string
  reftype  : string
  refname  : string
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Framelinvel {
  name     : string   # element name
  objtype  : string
  objname  : string
  reftype  : string
  refname  : string
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Frameangvel {
  name     : string   # element name
  objtype  : string
  objname  : string
  reftype  : string
  refname  : string
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Framelinacc {
  name     : string   # element name
  objtype  : string
  objname  : string
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Frameangacc {
  name     : string   # element name
  objtype  : string
  objname  : string
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Subtreecom {
  name     : string   # element name
  body     : string
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Subtreelinvel {
  name     : string   # element name
  body     : string
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Subtreeangmom {
  name     : string   # element name
  body     : string
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Insidesite {
  name     : string   # element name
  site     : ref<Site>
  objtype  : string
  objname  : string
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Distance {
  name     : string   # element name
  geom1    : ref<Geom>
  geom2    : ref<Geom>
  body1    : ref<Body>
  body2    : ref<Body>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Normal {
  name     : string   # element name
  geom1    : ref<Geom>
  geom2    : ref<Geom>
  body1    : ref<Body>
  body2    : ref<Body>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Fromto {
  name     : string   # element name
  geom1    : ref<Geom>
  geom2    : ref<Geom>
  body1    : ref<Body>
  body2    : ref<Body>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element SensorContact (xml="contact") {
  name     : string   # element name
  geom1    : ref<Geom>
  geom2    : ref<Geom>
  body1    : ref<Body>
  body2    : ref<Body>
  subtree1 : ref<Body>
  subtree2 : ref<Body>
  site     : ref<Site>
  num      : int32
  data     : string
  reduce   : ContactReduce
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element EPotential (xml="e_potential") {
  name     : string   # element name
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element EKinetic (xml="e_kinetic") {
  name     : string   # element name
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Clock {
  name     : string   # element name
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  cutoff   : double
  noise    : double
  user     : double[]
}

element Tactile {
  name     : string   # element name
  geom     : ref<Geom>
  mesh     : ref<Mesh>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[2]
  user     : double[]
}

element SensorUser (xml="user") {
  name      : string   # element name
  objtype   : string
  objname   : string
  datatype  : DataType
  needstage : NeedStage
  dim       : int32
  cutoff    : double
  noise     : double
  user      : double[]
}

element SensorPlugin (xml="plugin") {
  name     : string   # element name
  plugin   : string
  instance : ref<PluginInstance>
  cutoff   : double
  objtype  : string
  objname  : string
  reftype  : string
  refname  : string
  user     : double[]
  children config : Config *
}

element Keyframe {
  children keys : Key *
}

element Key {
  name  : string   # element name
  time  : double   # time
  qpos  : double[]   # qpos
  qvel  : double[]   # qvel
  act   : double[]   # act
  mpos  : double[]   # mocap pos
  mquat : double[]   # mocap quat
  ctrl  : double[]   # ctrl
}

element Frame {
  use Posed
  name   : string
  dclass : ref<Default> (xml="class")   # childclass applied to descendants
  children inertial : Inertial ?
  children joints : Joint *
  children freejoint : FreeJoint *
  children geoms : Geom *
  children attach : Attach *
  children sites : Site *
  children cameras : Camera *
  children lights : Light *
  children plugin : PluginRef *
  children composites : Composite *
  children flexcomps : Flexcomp *
}

