"""ProtoSpec -> mjSpec field-mapping emitter (Wave 1 of the mjSpec shim).

Generates the per-element field mapping the ProtoSpec->mjSpec compile path calls:
for each ProtoSpec element that corresponds to an ``mjs*`` struct, an
``ApplyMjs(const <Element>&, mjs<Struct>* out)`` that writes ONLY authored fields
(``ps::opt`` unset => the mjSpec default + defaults-class tree wins -- this is
load-bearing and must not be defeated by writing zeros for unauthored fields).

Ground truth is two snapshots:
  * ``schema/mujoco.spec`` (the ProtoSpec side), parsed via ``protospec_gen.idl``;
  * ``snapshots/mjspec_fields.json`` (the mjSpec side, extracted from mjspec.h).

Each element is either MAPPED (binds an mjsStruct) or whole-element WAIVED (in
``ELEMENT_WAIVERS``); every element must be in exactly one -- the mapped set is the
complement of the waiver partition. A mapped element's struct is the schema binding
``element X (mjs=mjsY)`` or the ``mjs<Name>`` identity (protospec_gen.binding). For
a mapped element every schema field is disposed as exactly one of: a special handler
(``name`` -> ``mjs_setName``; a ``variant`` field -> a hand helper in
``compile/mjs_convert.h``), an EXACT name match to a kind-compatible mjs field, an
ALIAS -- the field's ``mjs=`` binding annotation -- to a renamed kind-compatible mjs
field, or a WAIVER (a rule, or an explicit ``FIELD_WAIVERS`` entry) with a one-line
reason. Any field that is none of these fails generation with a named-field error --
that failure IS the maintenance contract (Task 3). The ``mjs=`` binding facts, being
inline on the field/element they describe, cannot be orphaned; the retained hand
tables (``FIELD_WAIVERS`` / ``VARIANT_HELPERS``) are still orphan-checked.

Output (``lib/generated/mjs_binding.{h,cc}``) MAY include ``<mujoco/mjspec.h>``:
unlike the other generated files it is compiled only by the MuJoCo-linked compile
target, never by the Tier-0 ``protospec`` library (see lib/CMakeLists.txt, which
lists generated sources explicitly and does not glob). The angle-bracket MuJoCo
include is invisible to the boundary gate's quoted-include scanner.

Conversions (documented per kind, DR cross-refs in the .spec):
  * opt scalar prim/enum -> direct write (enum via a generated ``ToMjt`` switch).
  * opt fixed ``std::array<T,N>`` -> element-wise copy into the mjs ``T[N]``.
  * opt range ``ps::InlineVec<T,hi>`` -> write the FILLED prefix only; the mjs
    array tail keeps its default (matches MJCF size/friction/solref semantics --
    e.g. a 1-element ``friction`` sets slide and leaves roll/spin at default).
  * opt unbounded ``std::vector<T>`` -> the opaque handle via a ``compile::Set*``
    helper (``mjs_setDouble``/``setInt``/``setFloat``, numeric-cast as needed).
  * opt ``std::string`` / ``ps::Ref<T>`` -> ``mjs_setString`` with the text/name.
  * ``std::vector<ps::Ref<T>>`` -> ``mjs_appendString`` per name (string vector).
  * orientation is already canonical quat in ProtoSpec, so ``quat``/``iquat`` map
    as plain fixed arrays; the mjs ``alt`` (mjsOrientation) stays default.
"""

from __future__ import annotations

import json
import os

from . import binding
from .emit import ident
from .idl import parse_spec

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SCHEMA = os.path.join(ROOT, "schema", "mujoco.spec")
FIELDS_JSON = os.path.join(ROOT, "snapshots", "mjspec_fields.json")
OUT_DIR = os.path.join(ROOT, "lib", "generated")

BANNER = "// Generated by protospec_gen.emit_mjs — do not edit."


class MjsCoverageError(Exception):
    """A schema field with no mapping/alias/waiver, or an orphaned table entry.

    This is the drift gate: it fires by name so a schema change that adds or
    renames a field (or drops one a table still references) breaks generation
    loudly instead of silently emitting for a stale field set."""


# --------------------------------------------------------------------------- #
# Element -> mjs struct map (MAPPED elements).                                 #
# --------------------------------------------------------------------------- #
# The element->mjsStruct join now lives in the schema: an element whose struct is
# `mjs<Name>` is identity (unannotated); any other struct is an explicit
# `element X (mjs=mjsY) { ... }` binding annotation (binding.element_struct). The
# MAPPED set is the complement of the retained ELEMENT_WAIVERS partition below --
# every element is in exactly one, enforced in _element_dispositions.


def _mapped_structs(schema):
    """{element-name -> mjsStruct} for every non-waived (mapped) element."""
    return {
        e["name"]: binding.element_struct(e)
        for e in schema["elements"]
        if e["name"] not in ELEMENT_WAIVERS
    }


# --------------------------------------------------------------------------- #
# Whole-element waivers: no per-instance mjs* struct.                          #
# --------------------------------------------------------------------------- #
ELEMENT_WAIVERS = {
    "Model": "root container; its physics/visual/size blocks fold into mjSpec + "
             "engine structs, its children map as their own elements",
    "LengthRange": "mjLROpt engine struct, embedded in mjsCompiler.LRopt",
    "Option": "mjOption engine struct (spec->option); not an mjs* struct",
    "Flag": "mjOption disable/enable bitflags; not an mjs* struct",
    "Size": "sizing scalars live directly on mjSpec (nkey/nuserdata/...)",
    "Statistic": "mjStatistic engine struct (spec->stat); not an mjs* struct",
    "Visual": "container for the mjVisual engine sub-blocks",
    "VisualGlobal": "mjVisual.global engine sub-struct; not an mjs* struct",
    "VisualQuality": "mjVisual.quality engine sub-struct; not an mjs* struct",
    "VisualHeadlight": "mjVisual.headlight engine sub-struct; not an mjs* struct",
    "VisualMap": "mjVisual.map engine sub-struct; not an mjs* struct",
    "VisualScale": "mjVisual.scale engine sub-struct; not an mjs* struct",
    "VisualRgba": "mjVisual.rgba engine sub-struct; not an mjs* struct",
    "Default": "mjsDefault is a container of child default specs; the class name "
               "is bound at mjs_addDefault and children map as their own elements",
    "Extension": "container for <plugin> definition blocks",
    "PluginDef": "engine plugin registration; not built through an mjs* struct",
    "PluginInstance": "plugin instance created via mjs_addPlugin + "
                      "mjs_setPluginAttributes by Wave 2, not a plain field write",
    "PluginRef": "geom/mesh/body sdf-plugin reference; bound via mjs_setPlugin* "
                 "on the owning element by Wave 2",
    "Config": "plugin key/value config; folded into mjsPlugin attributes",
    "Custom": "container for numeric/text/tuple",
    "Asset": "container for meshes/hfields/skins/textures/materials",
    "SkinBone": "bone rows fold into the mjsSkin parallel arrays "
                "(bodyname/bindpos/bindquat/vertid/vertweight) by Wave 2",
    "MaterialLayer": "layer rows fold into mjsMaterial.textures[role] by Wave 2",
    "ModelAsset": "child spec parsed via mj_parseXML + mjs_addSpec by Wave 4; "
                  "not an mjs* struct",
    "Attach": "native subtree attach via mjs_attach by Wave 4; not an mjs* struct",
    "Composite": "composite macro; no mjs* struct -- mjs_builder grafts a "
                 "re-parsed fragment (GraftComposite)",
    "CompositeJoint": "composite macro sub-element; consumed by GraftComposite",
    "CompositeSkin": "composite macro sub-element; consumed by GraftComposite",
    "CompositeGeom": "composite macro sub-element; consumed by GraftComposite",
    "CompositeSite": "composite macro sub-element; consumed by GraftComposite",
    "Flexcomp": "flexcomp macro; no mjs* struct -- mjs_builder expands via "
                "mjs_makeFlex (BuildFlexcomp)",
    "FlexcompEdge": "flexcomp macro sub-element; consumed by BuildFlexcomp",
    "FlexcompPin": "flexcomp macro sub-element; consumed by BuildFlexcomp",
    "FlexElasticity": "flex elasticity sub-block folded into mjsFlex by Wave 2",
    "FlexContact": "flex contact sub-block folded into mjsFlex by Wave 2",
    "FlexEdge": "flex edge sub-block folded into mjsFlex by Wave 2",
    "Replicate": "replicate macro; no mjs* struct -- mjs_builder mirrors the "
                 "reader expansion (ExpandReplicate)",
    "Deformable": "container for flexes/skins",
    "Contact": "container for pairs/excludes",
    "Equality": "container for equality constraints",
    "Tendon": "container for tendons",
    "SpatialSite": "spatial path item added via mjs_wrapSite by Wave 2",
    "SpatialGeom": "spatial path item added via mjs_wrapGeom by Wave 2",
    "Pulley": "spatial path item added via mjs_wrapPulley by Wave 2",
    "FixedJoint": "fixed-tendon joint added via mjs_wrapJoint by Wave 2",
    "Actuator": "container for actuators",
    "Sensor": "container for sensors",
    "Keyframe": "container for keyframes",
    "TupleElement": "tuple rows fold into mjsTuple.objtype/objname/objprm arrays",
}


# --------------------------------------------------------------------------- #
# Field -> mjs field renames now live in the schema.                          #
# --------------------------------------------------------------------------- #
# A non-identity attribute->mjs-field join is a `mjs=` binding annotation on the
# field (was ELEM_ALIAS for element-specific renames + GLOBAL_ALIAS for the
# cross-element rules like `user`->`userdata`). classify_field reads it via
# binding.field_mjs; a field with no annotation binds to the same-named mjs field.


# --------------------------------------------------------------------------- #
# Variant fields -> hand helpers in compile/mjs_convert.h.                     #
# --------------------------------------------------------------------------- #
VARIANT_HELPERS = {
    ("Geom", "shape"): "ApplyShape",
    ("Site", "shape"): "ApplyShape",
    ("Texture", "source"): "ApplyTextureSource",
}


# --------------------------------------------------------------------------- #
# Enum -> mjt ToMjt tables now live in the schema.                            #
# --------------------------------------------------------------------------- #
# An enum authored to mjSpec carries `ctype=<mjt*|int>`; each of its members maps
# to a C constant given by that member's `mjs_c=` (an override, or the sole source
# for an enum with no reader map) or, failing that, its reader `c=` value (75 of
# the joins are byte-identical to the keyword column and reuse it). A member
# flagged `no_mjs` is reader-only and excluded from the switch (the SO3 gain/bias
# members). emit_binding_cc reads the ordered (member, constant) pairs via
# binding.tomjt_members; compatible() gates enum-scalar writes on ctype presence.


# --------------------------------------------------------------------------- #
# Explicit per-field waivers (schema fields with no mjs counterpart).          #
# --------------------------------------------------------------------------- #
FIELD_WAIVERS = {
    ("Geom", "shellinertia"): "bool shortcut -> mjsGeom.typeinertia "
        "VOLUME/SHELL, set by Wave 2",
    ("Geom", "fluidshape"): "none/ellipsoid -> mjsGeom.fluid_ellipsoid 0/1, "
        "set by Wave 2",
    ("Camera", "output"): "CameraOutput keyword set -> mjsCamera.output bitmask, "
        "OR'd by Wave 2",
    ("Mesh", "builtin"): "no mjsMesh field; mjs_builder generates geometry via "
        "mjs_makeMesh(builtin, params)",
    ("Mesh", "params"): "no mjsMesh field; consumed by mjs_builder's "
        "mjs_makeMesh(builtin, params) call",
    ("Texture", "fileright"): "cube face file -> mjsTexture.cubefiles[0] by Wave 2",
    ("Texture", "fileleft"): "cube face file -> mjsTexture.cubefiles[1] by Wave 2",
    ("Texture", "fileup"): "cube face file -> mjsTexture.cubefiles[2] by Wave 2",
    ("Texture", "filedown"): "cube face file -> mjsTexture.cubefiles[3] by Wave 2",
    ("Texture", "filefront"): "cube face file -> mjsTexture.cubefiles[4] by Wave 2",
    ("Texture", "fileback"): "cube face file -> mjsTexture.cubefiles[5] by Wave 2",
    ("Texture", "gridlayout"): "string -> mjsTexture.gridlayout char[12] by Wave 2",
    ("Compiler", "coordinate"): "global coordinates removed from mjSpec",
    ("Compiler", "angle"): "radian/degree -> mjsCompiler.degree bool by Wave 2",
    ("Compiler", "strippath"): "path stripping lives on mjSpec.strippath",
    ("Compiler", "assetdir"): "no mjsCompiler field (asset dir handled elsewhere)",
    ("Compiler", "eulerseq"): "string -> mjsCompiler.eulerseq char[3] by Wave 2",
    ("Compiler", "alignfree"): "bool -> mjsCompiler.alignfree mjtAlignFree by Wave 2",
    ("Flex", "dof"): "FlexDof -> mjsFlex dof handling by Wave 2 (no scalar field)",
    ("Cylinder", "area"): "cylinder shortcut -> gain/bias via mjs_setToCylinder",
    ("Cylinder", "bias"): "cylinder shortcut -> gain/bias via mjs_setToCylinder",
    ("Cylinder", "timeconst"): "cylinder shortcut -> dynprm via mjs_setToCylinder",
    ("Position", "kp"): "position shortcut -> gain/bias via mjs_setToPosition",
    ("Position", "kv"): "position shortcut -> gain/bias via mjs_setToPosition",
    ("Position", "dampratio"): "position shortcut -> gain/bias via mjs_setToPosition",
    ("Position", "timeconst"): "position shortcut -> dynprm via mjs_setToPosition",
    ("Position", "inheritrange"): "position shortcut arg to mjs_setToPosition",
    ("IntVelocity", "kp"): "intvelocity shortcut -> mjs_setToIntVelocity",
    ("IntVelocity", "kv"): "intvelocity shortcut -> mjs_setToIntVelocity",
    ("IntVelocity", "dampratio"): "intvelocity shortcut -> mjs_setToIntVelocity",
    ("IntVelocity", "inheritrange"): "intvelocity shortcut arg to mjs_setToIntVelocity",
    ("Orientation", "kp"): "orientation shortcut -> mjs_setToOrientation",
    ("Orientation", "kv"): "orientation shortcut -> mjs_setToOrientation",
    ("Orientation", "dampratio"): "orientation shortcut -> mjs_setToOrientation",
    ("Orientation", "input"): "SO3 control chart -> mjsActuator.ctrlspec by builder",
    ("ActuatorGeneral", "input"): "SO3 control chart -> mjsActuator.ctrlspec by builder",
    ("Velocity", "kv"): "velocity shortcut -> gain/bias via mjs_setToVelocity",
    ("Damper", "kv"): "damper shortcut -> gain via mjs_setToDamper",
    ("Adhesion", "gain"): "adhesion shortcut -> gain via mjs_setToAdhesion",
    ("Muscle", "timeconst"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "tausmooth"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "range"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "force"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "scale"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "lmin"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "lmax"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "vmax"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "fpmax"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "fvmax"): "muscle shortcut -> mjs_setToMuscle",
    ("DcMotor", "motorconst"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "resistance"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "nominal"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "saturation"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "inductance"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "cogging"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "controller"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "thermal"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "lugre"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "input"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("ActuatorPlugin", "plugin"): "actuator plugin -> mjsActuator.plugin by Wave 2",
    ("ActuatorPlugin", "instance"): "actuator plugin instance -> mjsActuator.plugin",
    ("SensorPlugin", "plugin"): "sensor plugin -> mjsSensor.plugin by Wave 2",
    ("SensorPlugin", "instance"): "sensor plugin instance -> mjsSensor.plugin",
}


def _fields_of(struct):
    return {f["name"]: f for f in struct["fields"]}


# --------------------------------------------------------------------------- #
# Kind classification + compatibility (owned by protospec_gen.binding).        #
# --------------------------------------------------------------------------- #
ps_shape = binding.ps_shape


# --------------------------------------------------------------------------- #
# Per-field disposition.                                                        #
# --------------------------------------------------------------------------- #
def classify_field(elem_name, struct, struct_fields, f, used, ctype_enums):
    """Return one of:
        ("name",)                      -- element name via mjs_setName
        ("variant", helper)            -- variant field via a hand helper
        ("exact", mjs_field)
        ("alias", mjs_field)
        ("waive", reason)
    or raise MjsCoverageError if the field is unaccounted. `used` accumulates the
    hand-table keys actually consumed, for orphan detection. `struct` is the
    element's mjsStruct (from the schema binding); `ctype_enums` names the enums
    authored to mjSpec (gate for enum-scalar writes)."""
    name = f["name"]
    t = f["type"]
    key = (elem_name, name)

    if ps_shape(t) == "variant":
        helper = VARIANT_HELPERS.get(key)
        if helper is None:
            raise MjsCoverageError(
                f"{elem_name}.{name}: variant field has no VARIANT_HELPERS entry")
        used.add(("variant", key))
        return ("variant", helper)

    if name == "name" and ps_shape(t) == "string":
        return ("name",)

    if key in FIELD_WAIVERS:
        used.add(("fwaive", key))
        return ("waive", FIELD_WAIVERS[key])

    # Explicit `mjs=` rename annotation (was ELEM_ALIAS / GLOBAL_ALIAS): bind to
    # the named mjs field, kind-checked.
    mjs_name = binding.field_mjs(f)
    if mjs_name is not None:
        m = struct_fields.get(mjs_name)
        if m is None:
            raise MjsCoverageError(
                f"{elem_name}.{name}: mjs={mjs_name!r}: no such field of {struct}")
        if not binding.compatible(t, m, ctype_enums):
            raise MjsCoverageError(
                f"{elem_name}.{name}: mjs={mjs_name!r}: kind-incompatible")
        return ("alias", m)

    # Rule waiver: a default-class reference is bound at mjs_add*(def) time.
    if name == "dclass" and t["kind"] == "ref":
        return ("waive", "default class bound at mjs_add*(def) creation time")

    # Exact name match, kind-checked.
    m = struct_fields.get(name)
    if m is not None and m["name"] != "element" and binding.compatible(t, m, ctype_enums):
        return ("exact", m)

    # Rule waivers for the N:1 families, by field shape.
    if struct == "mjsSensor":
        if t["kind"] == "ref":
            return ("waive", "sensor object -> mjsSensor.objname/refname by Wave 2 "
                             "(objtype derived from sensor kind)")
        if name in ("objtype", "reftype"):
            return ("waive", "sensor object type -> mjsSensor.objtype/reftype "
                             "mjtObj by Wave 2")
        if name in ("data", "num", "reduce", "dim"):
            return ("waive", "sensor-kind parameter -> mjsSensor.intprm/dim by Wave 2")
    if struct == "mjsActuator":
        if t["kind"] == "ref":
            return ("waive", "transmission target -> mjsActuator.target/trntype "
                             "by Wave 2 (from the authored transmission field)")
    if struct == "mjsEquality":
        if t["kind"] == "ref" or name in ("anchor", "relpose", "polycoef", "cell",
                                          "torquescale"):
            return ("waive", "equality endpoints/data packed into "
                             "mjsEquality.name1/name2/objtype/data by Wave 2")

    raise MjsCoverageError(
        f"{elem_name}.{name}: no mapping, alias, or waiver (mjs struct "
        f"{struct!r} has no field {name!r})")


# --------------------------------------------------------------------------- #
# Coverage + orphan gate.                                                       #
# --------------------------------------------------------------------------- #
def _element_dispositions(schema, mjs):
    """Classify every field of every element; raise on any gap or orphan.
    Returns {element_name: (struct, [(field, disposition), ...])} for mapped
    elements."""
    struct_by = {s["name"]: s for s in mjs["structs"]}
    elem_by = {e["name"]: e for e in schema["elements"]}
    mapped = _mapped_structs(schema)  # {name -> mjsStruct}, non-waived elements
    ctype_enums = binding.ctype_enum_names(schema)

    # Every element is mapped XOR waived (partition invariant).
    for name in elem_by:
        if (name in mapped) == (name in ELEMENT_WAIVERS):
            if name in ELEMENT_WAIVERS:
                raise MjsCoverageError(
                    f"element {name!r} is both mapped (binds an mjsStruct) and "
                    "whole-element-waived (ELEMENT_WAIVERS)")
            raise MjsCoverageError(
                f"element {name!r} is neither mapped nor waived (ELEMENT_WAIVERS)")

    # Orphan: every waiver names a real element; every bound struct exists.
    for name in ELEMENT_WAIVERS:
        if name not in elem_by:
            raise MjsCoverageError(
                f"ELEMENT_WAIVERS names element {name!r} that no longer exists")
    for name, struct in mapped.items():
        if struct not in struct_by:
            raise MjsCoverageError(
                f"element {name!r} binds mjs struct {struct!r}: no such struct")

    dispositions = {}
    used = set()
    for name, struct in mapped.items():
        sf = _fields_of(struct_by[struct])
        rows = []
        for f in elem_by[name]["fields"]:
            rows.append((f, classify_field(name, struct, sf, f, used, ctype_enums)))
        dispositions[name] = (struct, rows)

    # Orphan: every retained hand-table entry must have been consumed.
    for key in FIELD_WAIVERS:
        if ("fwaive", key) not in used:
            raise MjsCoverageError(
                f"FIELD_WAIVERS entry {key} is dead (field/element gone)")
    for key in VARIANT_HELPERS:
        if ("variant", key) not in used:
            raise MjsCoverageError(
                f"VARIANT_HELPERS entry {key} is dead (field/element gone)")
    return dispositions


# --------------------------------------------------------------------------- #
# C++ emission.                                                                 #
# --------------------------------------------------------------------------- #
def _cast_ctype(m):
    """The mjs scalar field's C ctype (for enum static_cast)."""
    return m["ctype"]


def _emit_field(w, f, disp):
    """Emit the conversion for one field (already guarded on presence below)."""
    name = f["name"]
    t = f["type"]
    optional = f["optional"]
    val = f"(*e.{name})" if optional else f"e.{name}"
    guard = f"e.{name}.has_value()" if optional else None
    kind = disp[0]

    def line(body):
        if guard:
            w(f"  if ({guard}) {{ {body} }}")
        else:
            w(f"  {body}")

    if kind == "name":
        line(f"mjs_setName(out->element, {val}.c_str());")
        return
    if kind == "variant":
        line(f"ps::mjcf::compile::{disp[1]}({val}, out);")
        return

    if kind == "waive":
        return
    m = disp[1]  # exact / alias -> mjs field dict
    mk = m["kind"]
    mn = m["name"]
    shape = ps_shape(t)

    if shape in ("scalar",):
        line(f"out->{mn} = {val};")
    elif shape == "enum_scalar":
        line(f"out->{mn} = static_cast<{_cast_ctype(m)}>(ToMjt({val}));")
    elif shape in ("string",):
        line(f"mjs_setString(out->{mn}, {val}.c_str());")
    elif shape == "ref":
        line(f"mjs_setString(out->{mn}, {val}.name.c_str());")
    elif shape == "ref_list":
        line(f"ps::mjcf::compile::SetRefVec(out->{mn}, {val});")
    elif shape == "fixed":
        n = t["arity"]["size"]
        line(f"for (int i = 0; i < {n}; ++i) out->{mn}[i] = {val}[i];")
    elif shape == "range":
        line(f"for (std::size_t i = 0; i < {val}.size(); ++i) "
             f"out->{mn}[i] = {val}[i];")
    elif shape == "vec":
        helper = {"double_vec": "SetDouble", "int_vec": "SetInt",
                  "float_vec": "SetFloat"}[mk]
        line(f"ps::mjcf::compile::{helper}(out->{mn}, {val});")
    else:  # pragma: no cover -- guarded by compatible()
        raise MjsCoverageError(f"unhandled shape {shape} for {name}")


def emit_binding_h(dispositions):
    o = []
    w = o.append
    w(BANNER)
    w("//")
    w("// ApplyMjs(const <Element>&, mjs<Struct>*): write authored fields only.")
    w("// Compiled solely by the MuJoCo-linked compile target (never Tier-0).")
    w("#ifndef PROTOSPEC_GENERATED_MJS_BINDING_H")
    w("#define PROTOSPEC_GENERATED_MJS_BINDING_H")
    w("")
    w("#include <mujoco/mujoco.h>  // mjSpec structs + mjs_set* setter surface")
    w("")
    w('#include "types.h"')
    w("")
    w("namespace ps::mjcf {")
    w("")
    for name in sorted(dispositions):
        struct = dispositions[name][0]
        w(f"void ApplyMjs(const {name}& e, {struct}* out);")
    w("")
    w("}  // namespace ps::mjcf")
    w("")
    w("#endif  // PROTOSPEC_GENERATED_MJS_BINDING_H")
    return "\n".join(o) + "\n"


def emit_binding_cc(dispositions, enum_by):
    o = []
    w = o.append
    w(BANNER)
    w('#include "mjs_binding.h"')
    w("")
    w("#include <cstddef>")
    w("")
    w('#include "mjs_convert.h"')
    w("")
    w("namespace ps::mjcf {")
    w("namespace {")
    w("")

    # ToMjt overloads, one per enum actually used. Each enum's ordered (member,
    # constant) pairs come from its schema ctype/(c=)/(mjs_c=)/(no_mjs) annotations.
    used_enums = _enums_in_use(dispositions)
    enum_values = binding.load_enum_values()
    for enum in sorted(used_enums):
        members = binding.tomjt_members(enum_by[enum], enum_values)
        w(f"int ToMjt({enum} v) {{")
        w("  switch (v) {")
        for member, const in members:
            w(f"    case {enum}::{ident(member)}: return {const};")
        w("    default: return 0;")
        w("  }")
        w("}")
        w("")
    w("}  // namespace")
    w("")

    for name in sorted(dispositions):
        struct, rows = dispositions[name]
        w(f"void ApplyMjs(const {name}& e, {struct}* out) {{")
        for f, disp in rows:
            _emit_field(w, f, disp)
        w("  (void)e;")
        w("  (void)out;")
        w("}")
        w("")

    w("}  // namespace ps::mjcf")
    return "\n".join(o) + "\n"


def _enums_in_use(dispositions):
    enums = set()
    for _struct, rows in dispositions.values():
        for f, disp in rows:
            if disp[0] in ("exact", "alias") and ps_shape(f["type"]) == "enum_scalar":
                enums.add(f["type"]["name"])
    return enums


# --------------------------------------------------------------------------- #
# Public entry points.                                                          #
# --------------------------------------------------------------------------- #
def _load(schema=None, mjs=None):
    if schema is None:
        schema = parse_spec(SCHEMA).to_json()
    if mjs is None:
        with open(FIELDS_JSON, "r", encoding="utf-8") as fh:
            mjs = json.load(fh)
    return schema, mjs


def generate_files(schema=None, mjs=None):
    """Return {filename: content} for the generated mjs binding files. Raises
    MjsCoverageError on any coverage gap or orphaned table entry."""
    schema, mjs = _load(schema, mjs)
    structs = {s["name"]: {f["name"]: f for f in s["fields"]} for s in mjs["structs"]}
    binding.validate(schema, waivers=frozenset(ELEMENT_WAIVERS), filename=SCHEMA,
                     structs=structs)
    dispositions = _element_dispositions(schema, mjs)
    enum_by = {e["name"]: e for e in schema["enums"]}
    return {
        "mjs_binding.h": emit_binding_h(dispositions),
        "mjs_binding.cc": emit_binding_cc(dispositions, enum_by),
    }


def stats(schema=None, mjs=None):
    """Coverage statistics for reporting/tests: per-element (exact, aliased,
    waived, name, variant) counts, plus element mapped/waived totals."""
    schema, mjs = _load(schema, mjs)
    dispositions = _element_dispositions(schema, mjs)
    per = {}
    for name, (_struct, rows) in dispositions.items():
        c = {"exact": 0, "alias": 0, "waive": 0, "name": 0, "variant": 0}
        for _f, disp in rows:
            c[disp[0]] += 1
        per[name] = c
    return {
        "mapped_elements": len(dispositions),
        "waived_elements": len(ELEMENT_WAIVERS),
        "per_element": per,
    }
