"""ProtoSpec -> mjSpec field-mapping emitter (Wave 1 of the mjSpec shim).

Generates the per-element field mapping the ProtoSpec->mjSpec compile path calls:
for each ProtoSpec element that corresponds to an ``mjs*`` struct, an
``ApplyMjs(const <Element>&, mjs<Struct>* out)`` that writes ONLY authored fields
(``ps::opt`` unset => the mjSpec default + defaults-class tree wins -- this is
load-bearing and must not be defeated by writing zeros for unauthored fields).

Ground truth is two snapshots:
  * ``schema/mujoco.spec`` (the ProtoSpec side), parsed via ``protospec_gen.idl``;
  * ``snapshots/mjspec_fields.json`` (the mjSpec side, extracted from mjspec.h).

Each element is either MAPPED (in ``ELEMENT_STRUCT``) or whole-element WAIVED (in
``ELEMENT_WAIVERS``); every element must be in exactly one. For a mapped element
every schema field is disposed as exactly one of: a special handler (``name`` ->
``mjs_setName``; a ``variant`` field -> a hand helper in ``compile/mjs_convert.h``),
an EXACT name match to a kind-compatible mjs field, an ALIAS (``GLOBAL_ALIAS`` /
``ELEM_ALIAS``) to a renamed kind-compatible mjs field, or a WAIVER (a rule, or an
explicit ``FIELD_WAIVERS`` entry) with a one-line reason. Any field that is none of
these fails generation with a named-field error -- that failure IS the maintenance
contract (Task 3). The hand tables are orphan-checked: an alias/waiver naming a
schema field or mjs field that no longer exists also fails generation.

Output (``lib/generated/mjs_binding.{h,cc}``) MAY include ``<mujoco/mjspec.h>``:
unlike the other generated files it is compiled only by the MuJoCo-linked compile
target, never by the Tier-0 ``protospec`` library (see lib/CMakeLists.txt, which
lists generated sources explicitly and does not glob). The angle-bracket MuJoCo
include is invisible to the boundary gate's quoted-include scanner.

Conversions (documented per kind, DR cross-refs in the .spec):
  * opt scalar prim/enum -> direct write (enum via a generated ``ToMjt`` switch).
  * opt fixed ``std::array<T,N>`` -> element-wise copy into the mjs ``T[N]``.
  * opt range ``ps::InlineVec<T,hi>`` -> write the FILLED prefix only; the mjs
    array tail keeps its default (matches MJCF size/friction/solref semantics --
    e.g. a 1-element ``friction`` sets slide and leaves roll/spin at default).
  * opt unbounded ``std::vector<T>`` -> the opaque handle via a ``compile::Set*``
    helper (``mjs_setDouble``/``setInt``/``setFloat``, numeric-cast as needed).
  * opt ``std::string`` / ``ps::Ref<T>`` -> ``mjs_setString`` with the text/name.
  * ``std::vector<ps::Ref<T>>`` -> ``mjs_appendString`` per name (string vector).
  * orientation is already canonical quat in ProtoSpec, so ``quat``/``iquat`` map
    as plain fixed arrays; the mjs ``alt`` (mjsOrientation) stays default.
"""

from __future__ import annotations

import json
import os

from .emit import ident
from .idl import parse_spec

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SCHEMA = os.path.join(ROOT, "schema", "mujoco.spec")
FIELDS_JSON = os.path.join(ROOT, "snapshots", "mjspec_fields.json")
OUT_DIR = os.path.join(ROOT, "lib", "generated")

BANNER = "// Generated by protospec_gen.emit_mjs — do not edit."


class MjsCoverageError(Exception):
    """A schema field with no mapping/alias/waiver, or an orphaned table entry.

    This is the drift gate: it fires by name so a schema change that adds or
    renames a field (or drops one a table still references) breaks generation
    loudly instead of silently emitting for a stale field set."""


# --------------------------------------------------------------------------- #
# Element -> mjs struct map (MAPPED elements).                                 #
# --------------------------------------------------------------------------- #
ELEMENT_STRUCT = {
    "Body": "mjsBody",
    "Inertial": "mjsBody",          # folds into the body's i-frame fields
    "Frame": "mjsFrame",
    "Joint": "mjsJoint",
    "FreeJoint": "mjsJoint",        # type=free set by the builder
    "Geom": "mjsGeom",
    "Site": "mjsSite",
    "Camera": "mjsCamera",
    "Light": "mjsLight",
    "Mesh": "mjsMesh",
    "Hfield": "mjsHField",
    "Skin": "mjsSkin",
    "Texture": "mjsTexture",
    "Material": "mjsMaterial",
    "Pair": "mjsPair",
    "Exclude": "mjsExclude",
    "Connect": "mjsEquality",
    "Weld": "mjsEquality",
    "EqualityJoint": "mjsEquality",
    "EqualityTendon": "mjsEquality",
    "EqualityFlex": "mjsEquality",
    "Flexvert": "mjsEquality",
    "Flexstrain": "mjsEquality",
    "EqualityDefault": "mjsEquality",
    "Spatial": "mjsTendon",
    "Fixed": "mjsTendon",
    "TendonDefault": "mjsTendon",
    "Numeric": "mjsNumeric",
    "Text": "mjsText",
    "Tuple": "mjsTuple",
    "Key": "mjsKey",
    "Flex": "mjsFlex",
    "Compiler": "mjsCompiler",
    "ActuatorGeneral": "mjsActuator",
    "Motor": "mjsActuator",
    "Position": "mjsActuator",
    "Velocity": "mjsActuator",
    "IntVelocity": "mjsActuator",
    "Damper": "mjsActuator",
    "Cylinder": "mjsActuator",
    "Muscle": "mjsActuator",
    "Adhesion": "mjsActuator",
    "DcMotor": "mjsActuator",
    "ActuatorPlugin": "mjsActuator",
}
# Every SensorAny member maps to the single mjsSensor struct (its objtype/type
# are set by the Wave 2 builder from the sensor kind; the shared tail maps here).
_SENSORS = [
    "Touch", "Accelerometer", "Velocimeter", "Gyro", "Force", "Torque",
    "Magnetometer", "Camprojection", "Rangefinder", "Jointpos", "Jointvel",
    "Tendonpos", "Tendonvel", "Actuatorpos", "Actuatorvel", "Actuatorfrc",
    "Jointactuatorfrc", "Tendonactuatorfrc", "Ballquat", "Ballangvel",
    "Jointlimitpos", "Jointlimitvel", "Jointlimitfrc", "Tendonlimitpos",
    "Tendonlimitvel", "Tendonlimitfrc", "Framepos", "Framequat", "Framexaxis",
    "Frameyaxis", "Framezaxis", "Framelinvel", "Frameangvel", "Framelinacc",
    "Frameangacc", "Subtreecom", "Subtreelinvel", "Subtreeangmom", "Insidesite",
    "Distance", "Normal", "Fromto", "SensorContact", "EPotential", "EKinetic",
    "Clock", "Tactile", "SensorUser", "SensorPlugin",
]
for _s in _SENSORS:
    ELEMENT_STRUCT[_s] = "mjsSensor"


# --------------------------------------------------------------------------- #
# Whole-element waivers: no per-instance mjs* struct.                          #
# --------------------------------------------------------------------------- #
ELEMENT_WAIVERS = {
    "Model": "root container; its physics/visual/size blocks fold into mjSpec + "
             "engine structs, its children map as their own elements",
    "LengthRange": "mjLROpt engine struct, embedded in mjsCompiler.LRopt",
    "Option": "mjOption engine struct (spec->option); not an mjs* struct",
    "Flag": "mjOption disable/enable bitflags; not an mjs* struct",
    "Size": "sizing scalars live directly on mjSpec (nkey/nuserdata/...)",
    "Statistic": "mjStatistic engine struct (spec->stat); not an mjs* struct",
    "Visual": "container for the mjVisual engine sub-blocks",
    "VisualGlobal": "mjVisual.global engine sub-struct; not an mjs* struct",
    "VisualQuality": "mjVisual.quality engine sub-struct; not an mjs* struct",
    "VisualHeadlight": "mjVisual.headlight engine sub-struct; not an mjs* struct",
    "VisualMap": "mjVisual.map engine sub-struct; not an mjs* struct",
    "VisualScale": "mjVisual.scale engine sub-struct; not an mjs* struct",
    "VisualRgba": "mjVisual.rgba engine sub-struct; not an mjs* struct",
    "Default": "mjsDefault is a container of child default specs; the class name "
               "is bound at mjs_addDefault and children map as their own elements",
    "Extension": "container for <plugin> definition blocks",
    "PluginDef": "engine plugin registration; not built through an mjs* struct",
    "PluginInstance": "plugin instance created via mjs_addPlugin + "
                      "mjs_setPluginAttributes by Wave 2, not a plain field write",
    "PluginRef": "geom/mesh/body sdf-plugin reference; bound via mjs_setPlugin* "
                 "on the owning element by Wave 2",
    "Config": "plugin key/value config; folded into mjsPlugin attributes",
    "Custom": "container for numeric/text/tuple",
    "Asset": "container for meshes/hfields/skins/textures/materials",
    "SkinBone": "bone rows fold into the mjsSkin parallel arrays "
                "(bodyname/bindpos/bindquat/vertid/vertweight) by Wave 2",
    "MaterialLayer": "layer rows fold into mjsMaterial.textures[role] by Wave 2",
    "ModelAsset": "child spec parsed via mj_parseXML + mjs_addSpec by Wave 4; "
                  "not an mjs* struct",
    "Attach": "native subtree attach via mjs_attach by Wave 4; not an mjs* struct",
    "Composite": "composite macro; no mjs* struct -- mjs_builder grafts a "
                 "re-parsed fragment (GraftComposite)",
    "CompositeJoint": "composite macro sub-element; consumed by GraftComposite",
    "CompositeSkin": "composite macro sub-element; consumed by GraftComposite",
    "CompositeGeom": "composite macro sub-element; consumed by GraftComposite",
    "CompositeSite": "composite macro sub-element; consumed by GraftComposite",
    "Flexcomp": "flexcomp macro; no mjs* struct -- mjs_builder expands via "
                "mjs_makeFlex (BuildFlexcomp)",
    "FlexcompEdge": "flexcomp macro sub-element; consumed by BuildFlexcomp",
    "FlexcompPin": "flexcomp macro sub-element; consumed by BuildFlexcomp",
    "FlexElasticity": "flex elasticity sub-block folded into mjsFlex by Wave 2",
    "FlexContact": "flex contact sub-block folded into mjsFlex by Wave 2",
    "FlexEdge": "flex edge sub-block folded into mjsFlex by Wave 2",
    "Replicate": "replicate macro; no mjs* struct -- mjs_builder mirrors the "
                 "reader expansion (ExpandReplicate)",
    "Deformable": "container for flexes/skins",
    "Contact": "container for pairs/excludes",
    "Equality": "container for equality constraints",
    "Tendon": "container for tendons",
    "SpatialSite": "spatial path item added via mjs_wrapSite by Wave 2",
    "SpatialGeom": "spatial path item added via mjs_wrapGeom by Wave 2",
    "Pulley": "spatial path item added via mjs_wrapPulley by Wave 2",
    "FixedJoint": "fixed-tendon joint added via mjs_wrapJoint by Wave 2",
    "Actuator": "container for actuators",
    "Sensor": "container for sensors",
    "Keyframe": "container for keyframes",
    "TupleElement": "tuple rows fold into mjsTuple.objtype/objname/objprm arrays",
}


# --------------------------------------------------------------------------- #
# Alias tables (schema field -> mjs field).                                    #
# --------------------------------------------------------------------------- #
# GLOBAL_ALIAS applies to any mapped element whose target struct owns the mjs
# field (e.g. every element's `user` -> `userdata`); it is skipped where the
# struct has no such field.
GLOBAL_ALIAS = {
    "user": "userdata",
    "actuatorfrclimited": "actfrclimited",
    "actuatorfrcrange": "actfrcrange",
    "solreflimit": "solref_limit",
    "solimplimit": "solimp_limit",
    "solreffriction": "solref_friction",
    "solimpfriction": "solimp_friction",
}

# ELEM_ALIAS is (element, field) -> mjs field for element-specific renames.
ELEM_ALIAS = {
    ("Frame", "dclass"): "childclass",
    ("Inertial", "pos"): "ipos",   # inertial-frame position folds into mjsBody.ipos
    ("Inertial", "diaginertia"): "inertia",
    ("Joint", "actuatorgravcomp"): "actgravcomp",
    ("Geom", "hfield"): "hfieldname",
    ("Geom", "mesh"): "meshname",
    ("Geom", "fluidcoef"): "fluid_coefs",
    ("Camera", "target"): "targetbody",
    ("Camera", "focal"): "focal_length",
    ("Camera", "focalpixel"): "focal_pixel",
    ("Camera", "principal"): "principal_length",
    ("Camera", "principalpixel"): "principal_pixel",
    ("Camera", "sensorsize"): "sensor_size",
    ("Camera", "projection"): "proj",
    ("Light", "target"): "targetbody",
    ("Mesh", "vertex"): "uservert",
    ("Mesh", "normal"): "usernormal",
    ("Mesh", "texcoord"): "usertexcoord",
    ("Mesh", "face"): "userface",
    ("Pair", "geom1"): "geomname1",
    ("Pair", "geom2"): "geomname2",
    ("Exclude", "body1"): "bodyname1",
    ("Exclude", "body2"): "bodyname2",
    ("Flex", "body"): "vertbody",
    ("Flex", "node"): "nodebody",
    ("Flex", "vertex"): "vert",
    ("Flex", "element"): "elem",
    ("Hfield", "elevation"): "userdata",
    ("Skin", "vertex"): "vert",
}


# --------------------------------------------------------------------------- #
# Variant fields -> hand helpers in compile/mjs_convert.h.                     #
# --------------------------------------------------------------------------- #
VARIANT_HELPERS = {
    ("Geom", "shape"): "ApplyShape",
    ("Site", "shape"): "ApplyShape",
    ("Texture", "source"): "ApplyTextureSource",
}


# --------------------------------------------------------------------------- #
# Enum -> mjt value tables. Each ProtoSpec member maps to the mjt constant of   #
# the mjs field's ctype (verified against mjspec.h/mjtype.h). Members with no    #
# mjt counterpart are simply omitted (never authored through the shim).         #
# --------------------------------------------------------------------------- #
ENUM_MJT = {
    "GeomType": ("mjtGeom", {
        "plane": "mjGEOM_PLANE", "hfield": "mjGEOM_HFIELD", "sphere": "mjGEOM_SPHERE",
        "capsule": "mjGEOM_CAPSULE", "ellipsoid": "mjGEOM_ELLIPSOID",
        "cylinder": "mjGEOM_CYLINDER", "box": "mjGEOM_BOX", "mesh": "mjGEOM_MESH",
        "sdf": "mjGEOM_SDF"}),
    "JointType": ("mjtJoint", {
        "free": "mjJNT_FREE", "ball": "mjJNT_BALL", "slide": "mjJNT_SLIDE",
        "hinge": "mjJNT_HINGE"}),
    "TriState": ("mjtLimited", {
        "false_": "mjLIMITED_FALSE", "true_": "mjLIMITED_TRUE",
        "auto": "mjLIMITED_AUTO"}),
    "InertiaFromGeom": ("mjtInertiaFromGeom", {
        "false_": "mjINERTIAFROMGEOM_FALSE", "true_": "mjINERTIAFROMGEOM_TRUE",
        "auto": "mjINERTIAFROMGEOM_AUTO"}),
    "MeshInertia": ("mjtMeshInertia", {
        "convex": "mjMESH_INERTIA_CONVEX", "exact": "mjMESH_INERTIA_EXACT",
        "legacy": "mjMESH_INERTIA_LEGACY", "shell": "mjMESH_INERTIA_SHELL"}),
    "BodySleep": ("mjtSleepPolicy", {
        "auto": "mjSLEEP_AUTO", "never": "mjSLEEP_NEVER",
        "allowed": "mjSLEEP_ALLOWED", "init": "mjSLEEP_INIT"}),
    "CamLightMode": ("mjtCamLight", {
        "fixed": "mjCAMLIGHT_FIXED", "track": "mjCAMLIGHT_TRACK",
        "trackcom": "mjCAMLIGHT_TRACKCOM", "targetbody": "mjCAMLIGHT_TARGETBODY",
        "targetbodycom": "mjCAMLIGHT_TARGETBODYCOM"}),
    "CameraProjection": ("mjtProjection", {
        "perspective": "mjPROJ_PERSPECTIVE", "orthographic": "mjPROJ_ORTHOGRAPHIC"}),
    "LightType": ("mjtLightType", {
        "spot": "mjLIGHT_SPOT", "directional": "mjLIGHT_DIRECTIONAL",
        "point": "mjLIGHT_POINT", "image": "mjLIGHT_IMAGE"}),
    "TextureType": ("mjtTexture", {
        "twod": "mjTEXTURE_2D", "cube": "mjTEXTURE_CUBE", "skybox": "mjTEXTURE_SKYBOX"}),
    "ColorSpace": ("mjtColorSpace", {
        "auto": "mjCOLORSPACE_AUTO", "linear": "mjCOLORSPACE_LINEAR",
        "sRGB": "mjCOLORSPACE_SRGB"}),
    "TextureMark": ("mjtMark", {
        "none": "mjMARK_NONE", "edge": "mjMARK_EDGE", "cross": "mjMARK_CROSS",
        "random": "mjMARK_RANDOM"}),
    "DynType": ("mjtDyn", {
        "none": "mjDYN_NONE", "integrator": "mjDYN_INTEGRATOR",
        "filter": "mjDYN_FILTER", "filterexact": "mjDYN_FILTEREXACT",
        "muscle": "mjDYN_MUSCLE", "dcmotor": "mjDYN_DCMOTOR", "user": "mjDYN_USER"}),
    "GainType": ("mjtGain", {
        "fixed": "mjGAIN_FIXED", "affine": "mjGAIN_AFFINE", "muscle": "mjGAIN_MUSCLE",
        "dcmotor": "mjGAIN_DCMOTOR", "user": "mjGAIN_USER"}),
    "BiasType": ("mjtBias", {
        "none": "mjBIAS_NONE", "affine": "mjBIAS_AFFINE", "muscle": "mjBIAS_MUSCLE",
        "dcmotor": "mjBIAS_DCMOTOR", "user": "mjBIAS_USER"}),
    "DataType": ("mjtDataType", {
        "real": "mjDATATYPE_REAL", "positive": "mjDATATYPE_POSITIVE",
        "axis": "mjDATATYPE_AXIS", "quaternion": "mjDATATYPE_QUATERNION"}),
    "NeedStage": ("mjtStage", {
        "none": "mjSTAGE_NONE", "pos": "mjSTAGE_POS", "vel": "mjSTAGE_VEL",
        "acc": "mjSTAGE_ACC"}),
    # interp is a raw int order field (0=ZOH, 1=linear, 2=cubic), not an mjt enum.
    "InterpType": ("int", {"zoh": "0", "linear": "1", "cubic": "2"}),
}


# --------------------------------------------------------------------------- #
# Explicit per-field waivers (schema fields with no mjs counterpart).          #
# --------------------------------------------------------------------------- #
FIELD_WAIVERS = {
    ("Geom", "shellinertia"): "bool shortcut -> mjsGeom.typeinertia "
        "VOLUME/SHELL, set by Wave 2",
    ("Geom", "fluidshape"): "none/ellipsoid -> mjsGeom.fluid_ellipsoid 0/1, "
        "set by Wave 2",
    ("Camera", "output"): "CameraOutput keyword set -> mjsCamera.output bitmask, "
        "OR'd by Wave 2",
    ("Mesh", "builtin"): "no mjsMesh field; mjs_builder generates geometry via "
        "mjs_makeMesh(builtin, params)",
    ("Mesh", "params"): "no mjsMesh field; consumed by mjs_builder's "
        "mjs_makeMesh(builtin, params) call",
    ("Texture", "fileright"): "cube face file -> mjsTexture.cubefiles[0] by Wave 2",
    ("Texture", "fileleft"): "cube face file -> mjsTexture.cubefiles[1] by Wave 2",
    ("Texture", "fileup"): "cube face file -> mjsTexture.cubefiles[2] by Wave 2",
    ("Texture", "filedown"): "cube face file -> mjsTexture.cubefiles[3] by Wave 2",
    ("Texture", "filefront"): "cube face file -> mjsTexture.cubefiles[4] by Wave 2",
    ("Texture", "fileback"): "cube face file -> mjsTexture.cubefiles[5] by Wave 2",
    ("Texture", "gridlayout"): "string -> mjsTexture.gridlayout char[12] by Wave 2",
    ("Compiler", "coordinate"): "global coordinates removed from mjSpec",
    ("Compiler", "angle"): "radian/degree -> mjsCompiler.degree bool by Wave 2",
    ("Compiler", "strippath"): "path stripping lives on mjSpec.strippath",
    ("Compiler", "assetdir"): "no mjsCompiler field (asset dir handled elsewhere)",
    ("Compiler", "eulerseq"): "string -> mjsCompiler.eulerseq char[3] by Wave 2",
    ("Compiler", "alignfree"): "bool -> mjsCompiler.alignfree mjtAlignFree by Wave 2",
    ("Flex", "dof"): "FlexDof -> mjsFlex dof handling by Wave 2 (no scalar field)",
    ("Cylinder", "area"): "cylinder shortcut -> gain/bias via mjs_setToCylinder",
    ("Cylinder", "bias"): "cylinder shortcut -> gain/bias via mjs_setToCylinder",
    ("Cylinder", "timeconst"): "cylinder shortcut -> dynprm via mjs_setToCylinder",
    ("Position", "kp"): "position shortcut -> gain/bias via mjs_setToPosition",
    ("Position", "kv"): "position shortcut -> gain/bias via mjs_setToPosition",
    ("Position", "dampratio"): "position shortcut -> gain/bias via mjs_setToPosition",
    ("Position", "timeconst"): "position shortcut -> dynprm via mjs_setToPosition",
    ("Position", "inheritrange"): "position shortcut arg to mjs_setToPosition",
    ("IntVelocity", "kp"): "intvelocity shortcut -> mjs_setToIntVelocity",
    ("IntVelocity", "kv"): "intvelocity shortcut -> mjs_setToIntVelocity",
    ("IntVelocity", "dampratio"): "intvelocity shortcut -> mjs_setToIntVelocity",
    ("IntVelocity", "inheritrange"): "intvelocity shortcut arg to mjs_setToIntVelocity",
    ("Velocity", "kv"): "velocity shortcut -> gain/bias via mjs_setToVelocity",
    ("Damper", "kv"): "damper shortcut -> gain via mjs_setToDamper",
    ("Adhesion", "gain"): "adhesion shortcut -> gain via mjs_setToAdhesion",
    ("Muscle", "timeconst"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "tausmooth"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "range"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "force"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "scale"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "lmin"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "lmax"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "vmax"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "fpmax"): "muscle shortcut -> mjs_setToMuscle",
    ("Muscle", "fvmax"): "muscle shortcut -> mjs_setToMuscle",
    ("DcMotor", "motorconst"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "resistance"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "nominal"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "saturation"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "inductance"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "cogging"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "controller"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "thermal"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "lugre"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("DcMotor", "input"): "dcmotor shortcut -> mjs_setToDCMotor",
    ("ActuatorPlugin", "plugin"): "actuator plugin -> mjsActuator.plugin by Wave 2",
    ("ActuatorPlugin", "instance"): "actuator plugin instance -> mjsActuator.plugin",
    ("SensorPlugin", "plugin"): "sensor plugin -> mjsSensor.plugin by Wave 2",
    ("SensorPlugin", "instance"): "sensor plugin instance -> mjsSensor.plugin",
}


def _fields_of(struct):
    return {f["name"]: f for f in struct["fields"]}


# --------------------------------------------------------------------------- #
# Kind classification + compatibility.                                         #
# --------------------------------------------------------------------------- #
def ps_shape(t):
    """The ProtoSpec storage shape of a field type."""
    k = t["kind"]
    if k == "variant":
        return "variant"
    if k == "ref":
        return "ref_list" if t.get("arity") is not None else "ref"
    if k == "named":  # enum
        return "enum_set" if t.get("arity") is not None else "enum_scalar"
    # prim
    arity = t.get("arity")
    if t["prim"] == "string" and arity is None:
        return "string"
    if arity is None:
        return "scalar"
    return {"fixed": "fixed", "range": "range", "unbounded": "vec"}[arity["kind"]]


_VEC_KIND = {"double": "double_vec", "float": "float_vec", "int32": "int_vec",
             "uint64": "int_vec"}


def compatible(t, m):
    """True if a ProtoSpec field type `t` may be written into mjs field `m`
    (auto or alias). Kind is checked so a name collision with an unrelated mjs
    field (e.g. the identity `element` pointer, or an mjsFlex `node` handle of a
    different kind) is rejected -- it falls through to an explicit table."""
    shape = ps_shape(t)
    mk = m["kind"]
    if shape == "scalar":
        return mk == "scalar"
    if shape == "enum_scalar":
        return mk == "scalar" and t["name"] in ENUM_MJT
    if shape == "string":
        return mk == "string"
    if shape == "ref":
        return mk == "string"
    if shape == "ref_list":
        return mk == "string_vec"
    if shape == "fixed":
        return mk == "fixed_array" and m["array"]["value"] == t["arity"]["size"]
    if shape == "range":
        return mk == "fixed_array" and t["arity"]["max"] <= m["array"]["value"]
    if shape == "vec":
        if mk == _VEC_KIND.get(t["prim"]):
            return True
        # A double source may downcast into a float handle (mesh vertex/normal).
        return t["prim"] == "double" and mk == "float_vec"
    return False  # enum_set, variant


# --------------------------------------------------------------------------- #
# Per-field disposition.                                                        #
# --------------------------------------------------------------------------- #
def classify_field(elem_name, struct_fields, f, used):
    """Return one of:
        ("name",)                      -- element name via mjs_setName
        ("variant", helper)            -- variant field via a hand helper
        ("exact", mjs_field)
        ("alias", mjs_field)
        ("waive", reason)
    or raise MjsCoverageError if the field is unaccounted. `used` accumulates the
    hand-table keys actually consumed, for orphan detection."""
    name = f["name"]
    t = f["type"]
    key = (elem_name, name)

    if ps_shape(t) == "variant":
        helper = VARIANT_HELPERS.get(key)
        if helper is None:
            raise MjsCoverageError(
                f"{elem_name}.{name}: variant field has no VARIANT_HELPERS entry")
        used.add(("variant", key))
        return ("variant", helper)

    if name == "name" and ps_shape(t) == "string":
        return ("name",)

    if key in FIELD_WAIVERS:
        used.add(("fwaive", key))
        return ("waive", FIELD_WAIVERS[key])

    if key in ELEM_ALIAS:
        mjs_name = ELEM_ALIAS[key]
        m = struct_fields.get(mjs_name)
        if m is None:
            raise MjsCoverageError(
                f"ELEM_ALIAS[{key}] -> {mjs_name!r}: no such mjs field")
        if not compatible(t, m):
            raise MjsCoverageError(
                f"ELEM_ALIAS[{key}] -> {mjs_name!r}: kind-incompatible")
        used.add(("ealias", key))
        return ("alias", m)

    if name in GLOBAL_ALIAS and GLOBAL_ALIAS[name] in struct_fields:
        m = struct_fields[GLOBAL_ALIAS[name]]
        if compatible(t, m):
            used.add(("galias", name))
            return ("alias", m)

    # Rule waiver: a default-class reference is bound at mjs_add*(def) time.
    if name == "dclass" and t["kind"] == "ref":
        return ("waive", "default class bound at mjs_add*(def) creation time")

    # Exact name match, kind-checked.
    m = struct_fields.get(name)
    if m is not None and m["name"] != "element" and compatible(t, m):
        return ("exact", m)

    # Rule waivers for the N:1 families, by field shape.
    if elem_name in _SENSORS or ELEMENT_STRUCT.get(elem_name) == "mjsSensor":
        if t["kind"] == "ref":
            return ("waive", "sensor object -> mjsSensor.objname/refname by Wave 2 "
                             "(objtype derived from sensor kind)")
        if name in ("objtype", "reftype"):
            return ("waive", "sensor object type -> mjsSensor.objtype/reftype "
                             "mjtObj by Wave 2")
        if name in ("data", "num", "reduce", "dim"):
            return ("waive", "sensor-kind parameter -> mjsSensor.intprm/dim by Wave 2")
    if ELEMENT_STRUCT.get(elem_name) == "mjsActuator":
        if t["kind"] == "ref":
            return ("waive", "transmission target -> mjsActuator.target/trntype "
                             "by Wave 2 (from the authored transmission field)")
    if ELEMENT_STRUCT.get(elem_name) == "mjsEquality":
        if t["kind"] == "ref" or name in ("anchor", "relpose", "polycoef", "cell",
                                          "torquescale"):
            return ("waive", "equality endpoints/data packed into "
                             "mjsEquality.name1/name2/objtype/data by Wave 2")

    raise MjsCoverageError(
        f"{elem_name}.{name}: no mapping, alias, or waiver (mjs struct "
        f"{ELEMENT_STRUCT.get(elem_name)!r} has no field {name!r})")


# --------------------------------------------------------------------------- #
# Coverage + orphan gate.                                                       #
# --------------------------------------------------------------------------- #
def _element_dispositions(schema, mjs):
    """Classify every field of every element; raise on any gap or orphan.
    Returns {element_name: [(field, disposition), ...]} for mapped elements."""
    struct_by = {s["name"]: s for s in mjs["structs"]}
    elem_by = {e["name"]: e for e in schema["elements"]}

    for name in elem_by:
        mapped = name in ELEMENT_STRUCT
        waived = name in ELEMENT_WAIVERS
        if mapped and waived:
            raise MjsCoverageError(
                f"element {name!r} is both mapped and whole-element-waived")
        if not mapped and not waived:
            raise MjsCoverageError(
                f"element {name!r} is neither mapped (ELEMENT_STRUCT) nor waived "
                "(ELEMENT_WAIVERS)")

    # Orphan: every mapped/waived element name must be a real schema element.
    for name in list(ELEMENT_STRUCT) + list(ELEMENT_WAIVERS):
        if name not in elem_by:
            raise MjsCoverageError(
                f"table names element {name!r} that no longer exists in the schema")
    for name, struct in ELEMENT_STRUCT.items():
        if struct not in struct_by:
            raise MjsCoverageError(
                f"ELEMENT_STRUCT[{name!r}] -> {struct!r}: no such mjs struct")

    dispositions = {}
    used = set()
    for name, struct in ELEMENT_STRUCT.items():
        sf = _fields_of(struct_by[struct])
        rows = []
        for f in elem_by[name]["fields"]:
            rows.append((f, classify_field(name, sf, f, used)))
        dispositions[name] = rows

    # Orphan: every hand-table entry must have been consumed.
    for key in ELEM_ALIAS:
        if ("ealias", key) not in used:
            raise MjsCoverageError(
                f"ELEM_ALIAS entry {key} is dead (field/element gone)")
    for key in FIELD_WAIVERS:
        if ("fwaive", key) not in used:
            raise MjsCoverageError(
                f"FIELD_WAIVERS entry {key} is dead (field/element gone)")
    for key in VARIANT_HELPERS:
        if ("variant", key) not in used:
            raise MjsCoverageError(
                f"VARIANT_HELPERS entry {key} is dead (field/element gone)")
    for name in GLOBAL_ALIAS:
        if ("galias", name) not in used:
            raise MjsCoverageError(
                f"GLOBAL_ALIAS entry {name!r} is dead (never applied)")
    return dispositions


# --------------------------------------------------------------------------- #
# C++ emission.                                                                 #
# --------------------------------------------------------------------------- #
def _cast_ctype(m):
    """The mjs scalar field's C ctype (for enum static_cast)."""
    return m["ctype"]


def _emit_field(w, f, disp):
    """Emit the conversion for one field (already guarded on presence below)."""
    name = f["name"]
    t = f["type"]
    optional = f["optional"]
    val = f"(*e.{name})" if optional else f"e.{name}"
    guard = f"e.{name}.has_value()" if optional else None
    kind = disp[0]

    def line(body):
        if guard:
            w(f"  if ({guard}) {{ {body} }}")
        else:
            w(f"  {body}")

    if kind == "name":
        line(f"mjs_setName(out->element, {val}.c_str());")
        return
    if kind == "variant":
        line(f"ps::mjcf::compile::{disp[1]}({val}, out);")
        return

    if kind == "waive":
        return
    m = disp[1]  # exact / alias -> mjs field dict
    mk = m["kind"]
    mn = m["name"]
    shape = ps_shape(t)

    if shape in ("scalar",):
        line(f"out->{mn} = {val};")
    elif shape == "enum_scalar":
        line(f"out->{mn} = static_cast<{_cast_ctype(m)}>(ToMjt({val}));")
    elif shape in ("string",):
        line(f"mjs_setString(out->{mn}, {val}.c_str());")
    elif shape == "ref":
        line(f"mjs_setString(out->{mn}, {val}.name.c_str());")
    elif shape == "ref_list":
        line(f"ps::mjcf::compile::SetRefVec(out->{mn}, {val});")
    elif shape == "fixed":
        n = t["arity"]["size"]
        line(f"for (int i = 0; i < {n}; ++i) out->{mn}[i] = {val}[i];")
    elif shape == "range":
        line(f"for (std::size_t i = 0; i < {val}.size(); ++i) "
             f"out->{mn}[i] = {val}[i];")
    elif shape == "vec":
        helper = {"double_vec": "SetDouble", "int_vec": "SetInt",
                  "float_vec": "SetFloat"}[mk]
        line(f"ps::mjcf::compile::{helper}(out->{mn}, {val});")
    else:  # pragma: no cover -- guarded by compatible()
        raise MjsCoverageError(f"unhandled shape {shape} for {name}")


def emit_binding_h(dispositions):
    o = []
    w = o.append
    w(BANNER)
    w("//")
    w("// ApplyMjs(const <Element>&, mjs<Struct>*): write authored fields only.")
    w("// Compiled solely by the MuJoCo-linked compile target (never Tier-0).")
    w("#ifndef PROTOSPEC_GENERATED_MJS_BINDING_H")
    w("#define PROTOSPEC_GENERATED_MJS_BINDING_H")
    w("")
    w("#include <mujoco/mujoco.h>  // mjSpec structs + mjs_set* setter surface")
    w("")
    w('#include "types.h"')
    w("")
    w("namespace ps::mjcf {")
    w("")
    for name in sorted(dispositions):
        struct = ELEMENT_STRUCT[name]
        w(f"void ApplyMjs(const {name}& e, {struct}* out);")
    w("")
    w("}  // namespace ps::mjcf")
    w("")
    w("#endif  // PROTOSPEC_GENERATED_MJS_BINDING_H")
    return "\n".join(o) + "\n"


def emit_binding_cc(dispositions):
    o = []
    w = o.append
    w(BANNER)
    w('#include "mjs_binding.h"')
    w("")
    w("#include <cstddef>")
    w("")
    w('#include "mjs_convert.h"')
    w("")
    w("namespace ps::mjcf {")
    w("namespace {")
    w("")

    # ToMjt overloads, one per enum actually used.
    used_enums = _enums_in_use(dispositions)
    for enum in sorted(used_enums):
        ctype, members = ENUM_MJT[enum]
        w(f"int ToMjt({enum} v) {{")
        w("  switch (v) {")
        for member, const in members.items():
            w(f"    case {enum}::{ident(member)}: return {const};")
        w("    default: return 0;")
        w("  }")
        w("}")
        w("")
    w("}  // namespace")
    w("")

    for name in sorted(dispositions):
        struct = ELEMENT_STRUCT[name]
        w(f"void ApplyMjs(const {name}& e, {struct}* out) {{")
        for f, disp in dispositions[name]:
            _emit_field(w, f, disp)
        w("  (void)e;")
        w("  (void)out;")
        w("}")
        w("")

    w("}  // namespace ps::mjcf")
    return "\n".join(o) + "\n"


def _enums_in_use(dispositions):
    enums = set()
    for rows in dispositions.values():
        for f, disp in rows:
            if disp[0] in ("exact", "alias") and ps_shape(f["type"]) == "enum_scalar":
                enums.add(f["type"]["name"])
    return enums


# --------------------------------------------------------------------------- #
# Public entry points.                                                          #
# --------------------------------------------------------------------------- #
def _load(schema=None, mjs=None):
    if schema is None:
        schema = parse_spec(SCHEMA).to_json()
    if mjs is None:
        with open(FIELDS_JSON, "r", encoding="utf-8") as fh:
            mjs = json.load(fh)
    return schema, mjs


def generate_files(schema=None, mjs=None):
    """Return {filename: content} for the generated mjs binding files. Raises
    MjsCoverageError on any coverage gap or orphaned table entry."""
    schema, mjs = _load(schema, mjs)
    dispositions = _element_dispositions(schema, mjs)
    return {
        "mjs_binding.h": emit_binding_h(dispositions),
        "mjs_binding.cc": emit_binding_cc(dispositions),
    }


def stats(schema=None, mjs=None):
    """Coverage statistics for reporting/tests: per-element (exact, aliased,
    waived, name, variant) counts, plus element mapped/waived totals."""
    schema, mjs = _load(schema, mjs)
    dispositions = _element_dispositions(schema, mjs)
    per = {}
    for name, rows in dispositions.items():
        c = {"exact": 0, "alias": 0, "waive": 0, "name": 0, "variant": 0}
        for _f, disp in rows:
            c[disp[0]] += 1
        per[name] = c
    return {
        "mapped_elements": len(ELEMENT_STRUCT),
        "waived_elements": len(ELEMENT_WAIVERS),
        "per_element": per,
    }
