mujoco_version "3.10.1"

# ==========================================================================
# ProtoSpec IDL schema for MuJoCo MJCF (generated by
# tools/bootstrap/draft_schema.py, then hand-curated -- see plan Section 5).
# ==========================================================================

# --- Enums (keyword tables from the MJCF mjMap[] surface) ------------------

enum AngleUnit {
  radian         = "radian" (c=0)
  degree         = "degree" (c=1)
}

enum BiasType (ctype=mjtBias) {
  none           = "none" (c=mjBIAS_NONE)
  affine         = "affine" (c=mjBIAS_AFFINE)
  muscle         = "muscle" (c=mjBIAS_MUSCLE)
  dcmotor        = "dcmotor" (c=mjBIAS_DCMOTOR)
  so3            = "so3" (c=mjBIAS_SO3, no_mjs)
  user           = "user" (c=mjBIAS_USER)
}

enum BodySleep (ctype=mjtSleepPolicy) {
  auto           = "auto" (c=mjSLEEP_AUTO)
  never          = "never" (c=mjSLEEP_NEVER)
  allowed        = "allowed" (c=mjSLEEP_ALLOWED)
  init           = "init" (c=mjSLEEP_INIT)
}

enum CamLightMode (ctype=mjtCamLight) {
  fixed          = "fixed" (c=mjCAMLIGHT_FIXED)
  track          = "track" (c=mjCAMLIGHT_TRACK)
  trackcom       = "trackcom" (c=mjCAMLIGHT_TRACKCOM)
  targetbody     = "targetbody" (c=mjCAMLIGHT_TARGETBODY)
  targetbodycom  = "targetbodycom" (c=mjCAMLIGHT_TARGETBODYCOM)
}

enum CameraOutput {
  rgb            = "rgb" (c=mjCAMOUT_RGB)
  depth          = "depth" (c=mjCAMOUT_DEPTH)
  distance       = "distance" (c=mjCAMOUT_DIST)
  normal         = "normal" (c=mjCAMOUT_NORMAL)
  segmentation   = "segmentation" (c=mjCAMOUT_SEG)
}

enum CameraProjection (ctype=mjtProjection) {
  perspective    = "perspective" (c=mjPROJ_PERSPECTIVE)
  orthographic   = "orthographic" (c=mjPROJ_ORTHOGRAPHIC)
}

enum ColorSpace (ctype=mjtColorSpace) {
  auto           = "auto" (c=mjCOLORSPACE_AUTO)
  linear         = "linear" (c=mjCOLORSPACE_LINEAR)
  sRGB           = "sRGB" (c=mjCOLORSPACE_SRGB)
}

enum CompositeType {
  particle       = "particle" (c=mjCOMPTYPE_PARTICLE)
  grid           = "grid" (c=mjCOMPTYPE_GRID)
  rope           = "rope" (c=mjCOMPTYPE_ROPE)
  loop           = "loop" (c=mjCOMPTYPE_LOOP)
  cable          = "cable" (c=mjCOMPTYPE_CABLE)
  cloth          = "cloth" (c=mjCOMPTYPE_CLOTH)
}

enum Cone {
  pyramidal      = "pyramidal" (c=mjCONE_PYRAMIDAL)
  elliptic       = "elliptic" (c=mjCONE_ELLIPTIC)
}

enum Conflict (ctype=mjtConflict) {
  warning        = "warning" (c=mjCONFLICT_WARNING)
  merge          = "merge" (c=mjCONFLICT_MERGE)
  error          = "error" (c=mjCONFLICT_ERROR)
}

enum ContactData {
  found          = "found" (c=mjCONDATA_FOUND)
  force          = "force" (c=mjCONDATA_FORCE)
  torque         = "torque" (c=mjCONDATA_TORQUE)
  dist           = "dist" (c=mjCONDATA_DIST)
  pos            = "pos" (c=mjCONDATA_POS)
  normal         = "normal" (c=mjCONDATA_NORMAL)
  tangent        = "tangent" (c=mjCONDATA_TANGENT)
}

enum ContactReduce {
  none           = "none" (c=0)
  mindist        = "mindist" (c=1)
  maxforce       = "maxforce" (c=2)
  netforce       = "netforce" (c=3)
}

enum Coordinate {
  local          = "local" (c=0)
  global         = "global" (c=1)
}

enum DataType (ctype=mjtDataType) {
  real           = "real" (c=mjDATATYPE_REAL)
  positive       = "positive" (c=mjDATATYPE_POSITIVE)
  axis           = "axis" (c=mjDATATYPE_AXIS)
  quaternion     = "quaternion" (c=mjDATATYPE_QUATERNION)
}

enum DcMotorInput {
  voltage        = "voltage" (c=0)
  position       = "position" (c=1)
  velocity       = "velocity" (c=2)
}

enum SO3Input {
  expmap         = "expmap" (c=mjCHART_EXPMAP)
  quat           = "quat" (c=mjCHART_QUAT)
}

enum DynType (ctype=mjtDyn) {
  none           = "none" (c=mjDYN_NONE)
  integrator     = "integrator" (c=mjDYN_INTEGRATOR)
  filter         = "filter" (c=mjDYN_FILTER)
  filterexact    = "filterexact" (c=mjDYN_FILTEREXACT)
  muscle         = "muscle" (c=mjDYN_MUSCLE)
  dcmotor        = "dcmotor" (c=mjDYN_DCMOTOR)
  user           = "user" (c=mjDYN_USER)
}

enum Elastic2D {
  none           = "none" (c=0)
  bend           = "bend" (c=1)
  stretch        = "stretch" (c=2)
  both           = "both" (c=3)
}

enum FlexDof {
  full           = "full" (c=mjFCOMPDOF_FULL)
  radial         = "radial" (c=mjFCOMPDOF_RADIAL)
  trilinear      = "trilinear" (c=mjFCOMPDOF_TRILINEAR)
  quadratic      = "quadratic" (c=mjFCOMPDOF_QUADRATIC)
  twod           = "2d" (c=mjFCOMPDOF_2D)
}

enum FlexEquality {
  false_         = "false" (c=0)
  true_          = "true" (c=1)
  vert           = "vert" (c=2)
  strain         = "strain" (c=3)
}

enum FlexSelfCollide {
  none           = "none" (c=mjFLEXSELF_NONE)
  narrow         = "narrow" (c=mjFLEXSELF_NARROW)
  bvh            = "bvh" (c=mjFLEXSELF_BVH)
  sap            = "sap" (c=mjFLEXSELF_SAP)
  auto           = "auto" (c=mjFLEXSELF_AUTO)
}

enum FlexcompType {
  grid           = "grid" (c=mjFCOMPTYPE_GRID)
  box            = "box" (c=mjFCOMPTYPE_BOX)
  cylinder       = "cylinder" (c=mjFCOMPTYPE_CYLINDER)
  ellipsoid      = "ellipsoid" (c=mjFCOMPTYPE_ELLIPSOID)
  square         = "square" (c=mjFCOMPTYPE_SQUARE)
  disc           = "disc" (c=mjFCOMPTYPE_DISC)
  circle         = "circle" (c=mjFCOMPTYPE_CIRCLE)
  mesh           = "mesh" (c=mjFCOMPTYPE_MESH)
  gmsh           = "gmsh" (c=mjFCOMPTYPE_GMSH)
  direct         = "direct" (c=mjFCOMPTYPE_DIRECT)
}

enum FluidShape {
  none           = "none" (c=0)
  ellipsoid      = "ellipsoid" (c=1)
}

enum GainType (ctype=mjtGain) {
  fixed          = "fixed" (c=mjGAIN_FIXED)
  affine         = "affine" (c=mjGAIN_AFFINE)
  muscle         = "muscle" (c=mjGAIN_MUSCLE)
  dcmotor        = "dcmotor" (c=mjGAIN_DCMOTOR)
  so3            = "so3" (c=mjGAIN_SO3, no_mjs)
  user           = "user" (c=mjGAIN_USER)
}

enum GeomType (ctype=mjtGeom) {
  plane          = "plane" (c=mjGEOM_PLANE)
  hfield         = "hfield" (c=mjGEOM_HFIELD)
  sphere         = "sphere" (c=mjGEOM_SPHERE)
  capsule        = "capsule" (c=mjGEOM_CAPSULE)
  ellipsoid      = "ellipsoid" (c=mjGEOM_ELLIPSOID)
  cylinder       = "cylinder" (c=mjGEOM_CYLINDER)
  box            = "box" (c=mjGEOM_BOX)
  mesh           = "mesh" (c=mjGEOM_MESH)
  sdf            = "sdf" (c=mjGEOM_SDF)
}

enum InertiaFromGeom (ctype=mjtInertiaFromGeom) {
  false_         = "false" (mjs_c=mjINERTIAFROMGEOM_FALSE)
  true_          = "true" (mjs_c=mjINERTIAFROMGEOM_TRUE)
  auto           = "auto" (mjs_c=mjINERTIAFROMGEOM_AUTO)
}

enum Integrator {
  Euler          = "Euler" (c=mjINT_EULER)
  RK4            = "RK4" (c=mjINT_RK4)
  implicit       = "implicit" (c=mjINT_IMPLICIT)
  implicitfast   = "implicitfast" (c=mjINT_IMPLICITFAST)
}

enum InterpType (ctype=int) {
  zoh            = "zoh" (c=0)
  linear         = "linear" (c=1)
  cubic          = "cubic" (c=2)
}

enum JacobianType {
  dense          = "dense" (c=mjJAC_DENSE)
  sparse         = "sparse" (c=mjJAC_SPARSE)
  auto           = "auto" (c=mjJAC_AUTO)
}

enum JointType (ctype=mjtJoint) {
  free           = "free" (c=mjJNT_FREE)
  ball           = "ball" (c=mjJNT_BALL)
  slide          = "slide" (c=mjJNT_SLIDE)
  hinge          = "hinge" (c=mjJNT_HINGE)
}

enum LRMode {
  none           = "none" (c=mjLRMODE_NONE)
  muscle         = "muscle" (c=mjLRMODE_MUSCLE)
  muscleuser     = "muscleuser" (c=mjLRMODE_MUSCLEUSER)
  all            = "all" (c=mjLRMODE_ALL)
}

enum LightType (ctype=mjtLightType) {
  spot           = "spot" (c=mjLIGHT_SPOT)
  directional    = "directional" (c=mjLIGHT_DIRECTIONAL)
  point          = "point" (c=mjLIGHT_POINT)
  image          = "image" (c=mjLIGHT_IMAGE)
}

enum MeshBuiltin {
  none           = "none" (c=mjMESH_BUILTIN_NONE)
  sphere         = "sphere" (c=mjMESH_BUILTIN_SPHERE)
  hemisphere     = "hemisphere" (c=mjMESH_BUILTIN_HEMISPHERE)
  cone           = "cone" (c=mjMESH_BUILTIN_CONE)
  supertorus     = "supertorus" (c=mjMESH_BUILTIN_SUPERTORUS)
  supersphere    = "supersphere" (c=mjMESH_BUILTIN_SUPERSPHERE)
  wedge          = "wedge" (c=mjMESH_BUILTIN_WEDGE)
  plate          = "plate" (c=mjMESH_BUILTIN_PLATE)
}

enum MeshInertia (ctype=mjtMeshInertia) {
  convex         = "convex" (c=mjMESH_INERTIA_CONVEX)
  legacy         = "legacy" (c=mjMESH_INERTIA_LEGACY)
  exact          = "exact" (c=mjMESH_INERTIA_EXACT)
  shell          = "shell" (c=mjMESH_INERTIA_SHELL)
}

enum NeedStage (ctype=mjtStage) {
  none           = "none" (c=mjSTAGE_NONE)
  pos            = "pos" (c=mjSTAGE_POS)
  vel            = "vel" (c=mjSTAGE_VEL)
  acc            = "acc" (c=mjSTAGE_ACC)
}

enum RayData {
  dist           = "dist" (c=mjRAYDATA_DIST)
  dir            = "dir" (c=mjRAYDATA_DIR)
  origin         = "origin" (c=mjRAYDATA_ORIGIN)
  point          = "point" (c=mjRAYDATA_POINT)
  normal         = "normal" (c=mjRAYDATA_NORMAL)
  depth          = "depth" (c=mjRAYDATA_DEPTH)
}

enum SimpleMode (ctype=mjtByte) {
  false_         = "false" (c=0)
  auto           = "auto" (c=1)
}

enum SolverType {
  PGS            = "PGS" (c=mjSOL_PGS)
  CG             = "CG" (c=mjSOL_CG)
  Newton         = "Newton" (c=mjSOL_NEWTON)
}

enum TexRole {
  rgb            = "rgb" (c=mjTEXROLE_RGB)
  occlusion      = "occlusion" (c=mjTEXROLE_OCCLUSION)
  roughness      = "roughness" (c=mjTEXROLE_ROUGHNESS)
  metallic       = "metallic" (c=mjTEXROLE_METALLIC)
  normal         = "normal" (c=mjTEXROLE_NORMAL)
  opacity        = "opacity" (c=mjTEXROLE_OPACITY)
  emissive       = "emissive" (c=mjTEXROLE_EMISSIVE)
  rgba           = "rgba" (c=mjTEXROLE_RGBA)
  orm            = "orm" (c=mjTEXROLE_ORM)
}

enum TextureBuiltin {
  none           = "none" (c=mjBUILTIN_NONE)
  gradient       = "gradient" (c=mjBUILTIN_GRADIENT)
  checker        = "checker" (c=mjBUILTIN_CHECKER)
  flat           = "flat" (c=mjBUILTIN_FLAT)
}

enum TextureMark (ctype=mjtMark) {
  none           = "none" (c=mjMARK_NONE)
  edge           = "edge" (c=mjMARK_EDGE)
  cross          = "cross" (c=mjMARK_CROSS)
  random         = "random" (c=mjMARK_RANDOM)
}

enum TextureType (ctype=mjtTexture) {
  twod           = "2d" (c=mjTEXTURE_2D)
  cube           = "cube" (c=mjTEXTURE_CUBE)
  skybox         = "skybox" (c=mjTEXTURE_SKYBOX)
}

enum TriState (ctype=mjtLimited, cmap=TFAuto_map) {
  false_         = "false" (mjs_c=mjLIMITED_FALSE)
  true_          = "true" (mjs_c=mjLIMITED_TRUE)
  auto           = "auto" (mjs_c=mjLIMITED_AUTO)
}

# --- Shape / texture variants (DR-3) + canonical orientation --------------

# Orientation is canonicalized to a single unit quaternion at read time
# (Q-ORIENT, docs/plan_canonicalization.md Wave A): the reader accepts all five
# MJCF spellings and folds euler/axisangle/xyaxes/zaxis into `quat` against the
# effective compiler.angle/eulerseq. The four non-canonical spellings are
# read-only input aliases (see the `aliases` annotation on each canonical
# `quat`/`iquat`); the writer emits `quat` only.

struct Explicit { size : double[0..3] }
struct FromTo   { fromto : double[6] }
variant GeomShape {
  explicit : Explicit     # type-specific size, at the element's own pose
  fromto   : FromTo       # capsule/cylinder/box/ellipsoid endpoints
}

struct TexFile { file : string }
variant TextureSource {
  builtin : TextureBuiltin   # procedural generator
  file    : TexFile          # single image file (buffer form is API-only)
}

mixin Posed {
  pos  : double[3] = {0, 0, 0}   # position offset
  quat : double[4] (aliases="euler axisangle xyaxes zaxis", resolver=orientation)   # orientation (canonical quat; also accepts euler/axisangle/xyaxes/zaxis)
}

# Shared trailing block of most <sensor> elements (appended via `use` after each
# sensor's own discriminating ref fields; the three that diverge -- Tactile,
# SensorUser, SensorPlugin -- spell their tails locally). Field order here is the
# emitted attribute / field-id order, so it must stay verbatim.
mixin SensorTail {
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[0..2]
  cutoff   : double
  noise    : double
  user     : double[] (mjs=userdata)
}

# Shared leading block of every <actuator> element except <plugin> (which
# interposes plugin/instance): identity + history-buffer fields.
mixin ActuatorHead {
  name          : string   # element name
  dclass        : ref<Default> (xml="class")   # default class
  group         : int32   # group
  nsample       : int32   # number of samples in history buffer
  interp        : InterpType   # interpolation order (0=ZOH, 1=linear, 2=cubic)
  delay         : double   # delay time in seconds; 0: no delay
}

# Shared transmission block of the eight actuators that carry the full set, in the
# canonical order between their limit fields and their element-specific tail.
# Muscle (no site/refsite), Adhesion (no transmission) and <plugin> (reordered)
# spell their transmissions locally.
mixin Transmission {
  gear          : double[0..6] = {1}   # length and transmitted force scaling
  damping       : double[0..3]   # damping coefficients
  armature      : double (lenient)   # armature inertia
  cranklength   : double   # crank length, for slider-crank
  user          : double[] (mjs=userdata)   # user data
  joint         : ref<Joint>
  jointinparent : ref<Joint>
  tendon        : ref<TendonAny>
  slidersite    : ref<Site>   # site defining cylinder, for slider-crank
  cranksite     : ref<Site>
  site          : ref<Site>
  refsite       : ref<Site>   # reference site, for site transmission
}

# --- Unions (ordered heterogeneous child lists / any-of refs) -------------

union ActuatorAny =
    ActuatorGeneral
  | Motor
  | Position
  | Velocity
  | IntVelocity
  | Orientation
  | Damper
  | Cylinder
  | Muscle
  | Adhesion
  | DcMotor
  | ActuatorPlugin

union SensorAny =
    Touch
  | Accelerometer
  | Velocimeter
  | Gyro
  | Force
  | Torque
  | Magnetometer
  | Camprojection
  | Rangefinder
  | Jointpos
  | Jointvel
  | Tendonpos
  | Tendonvel
  | Actuatorpos
  | Actuatorvel
  | Actuatorfrc
  | Jointactuatorfrc
  | Tendonactuatorfrc
  | Ballquat
  | Ballangvel
  | Jointlimitpos
  | Jointlimitvel
  | Jointlimitfrc
  | Tendonlimitpos
  | Tendonlimitvel
  | Tendonlimitfrc
  | Framepos
  | Framequat
  | Framexaxis
  | Frameyaxis
  | Framezaxis
  | Framelinvel
  | Frameangvel
  | Framelinacc
  | Frameangacc
  | Subtreecom
  | Subtreelinvel
  | Subtreeangmom
  | Insidesite
  | Distance
  | Normal
  | Fromto
  | SensorContact
  | EPotential
  | EKinetic
  | Clock
  | Tactile
  | SensorUser
  | SensorPlugin

union EqualityAny =
    Connect
  | Weld
  | EqualityJoint
  | EqualityTendon
  | EqualityFlex
  | Flexvert
  | Flexstrain

union TendonAny =
    Spatial
  | Fixed

union PathItemAny =
    SpatialSite
  | SpatialGeom
  | Pulley

# Every body child whose document order affects MuJoCo's id assignment shares
# one ordered union list. MuJoCo walks a body's children in document order,
# assigning geom/joint/site/... ids as it goes and splicing a <frame>'s contents
# (and the pass-through macros' expansions) into the enclosing body at their
# authored position. Per-type lists lose that interleave -- e.g. a <geom> before
# a <frame> that itself holds a <geom> compiles to a different geom id order than
# the reverse -- so all id-producing children (and the body/frame/macro nodes
# that create or wrap them) are one union; only the unique <inertial> stays a
# separate optional child (it produces no id and its position is irrelevant).
union BodyChildAny =
    Geom
  | Joint
  | FreeJoint
  | Site
  | Camera
  | Light
  | PluginRef
  | Body
  | Frame
  | Composite
  | Flexcomp
  | Replicate
  | Attach

# --- Elements -------------------------------------------------------------

element Model (xml="mujoco") {
  model : string
  children compilers : Compiler *
  children options : Option *
  children sizes : Size *
  children visuals : Visual *
  children statistics : Statistic *
  children defaults : Default *
  children extensions : Extension *
  children customs : Custom *
  children assets : Asset *
  children worldbody : Body *
  children deformables : Deformable *
  children contacts : Contact *
  children equalitys : Equality *
  children tendons : Tendon *
  children actuators : Actuator *
  children sensors : Sensor *
  children keyframes : Keyframe *
}

element Compiler {
  autolimits        : bool   # infer "limited" attribute based on range
  boundmass         : double   # enforce minimum body mass
  boundinertia      : double   # enforce minimum body diagonal inertia
  settotalmass      : double   # rescale masses and inertias; <=0: ignore
  balanceinertia    : bool   # automatically impose A + B >= C rule
  strippath         : bool
  coordinate        : Coordinate
  angle             : AngleUnit
  fitaabb           : bool   # meshfit to aabb instead of inertia box
  eulerseq          : string   # sequence for euler rotations
  meshdir           : string   # mesh and hfield directory
  texturedir        : string   # texture directory
  discardvisual     : bool   # discard visual geoms in parser
  usethread         : bool   # use multiple threads to speed up compiler
  fusestatic        : bool   # fuse static bodies with parent
  inertiafromgeom   : InertiaFromGeom   # use geom inertias (mjtInertiaFromGeom)
  inertiagrouprange : int32[2]   # range of geom groups used to compute inertia
  saveinertial      : bool   # save explicit inertial clause for all bodies to XML
  assetdir          : string
  alignfree         : bool   # align free joints with inertial frame
  conflict          : Conflict = warning   # conflict resolution for attach (mjtConflict)
  children lengthRanges : LengthRange ?
}

element LengthRange {
  mode        : LRMode
  useexisting : bool
  uselimit    : bool
  accel       : double
  maxforce    : double
  timeconst   : double
  timestep    : double
  inttotal    : double
  interval    : double
  tolrange    : double
}

element Option {
  timestep             : double
  impratio             : double
  tolerance            : double
  ls_tolerance         : double
  noslip_tolerance     : double
  ccd_tolerance        : double
  sleep_tolerance      : double
  gravity              : double[3]
  wind                 : double[3]
  magnetic             : double[3]
  density              : double
  viscosity            : double
  o_margin             : double
  o_solref             : double[2]
  o_solimp             : double[5]
  o_friction           : double[5]
  integrator           : Integrator
  cone                 : Cone
  jacobian             : JacobianType
  solver               : SolverType
  iterations           : int32
  ls_iterations        : int32
  noslip_iterations    : int32
  ccd_iterations       : int32
  sdf_iterations       : int32
  sdf_initpoints       : int32
  actuatorgroupdisable : int32[]
  children flags : Flag ?
}

element Flag {
  constraint   : bool
  equality     : bool
  frictionloss : bool
  limit        : bool
  contact      : bool
  spring       : bool
  damper       : bool
  gravity      : bool
  clampctrl    : bool
  warmstart    : bool
  filterparent : bool
  actuation    : bool
  refsafe      : bool
  sensor       : bool
  midphase     : bool
  eulerdamp    : bool
  autoreset    : bool
  nativeccd    : bool
  island       : bool
  override     : bool
  energy       : bool
  fwdinv       : bool
  invdiscrete  : bool
  multiccd     : bool
  sleep        : bool
  diagexact    : bool
}

element Size {
  memory         : string
  njmax          : int32
  nconmax        : int32
  nstack         : int32
  nuserdata      : int32
  nkey           : int32
  nuser_body     : int32
  nuser_jnt      : int32
  nuser_geom     : int32
  nuser_site     : int32
  nuser_cam      : int32
  nuser_tendon   : int32
  nuser_actuator : int32
  nuser_sensor   : int32
}

element Visual {
  children visualGlobals : VisualGlobal ?
  children visualQualitys : VisualQuality ?
  children visualHeadlights : VisualHeadlight ?
  children visualMaps : VisualMap ?
  children visualScales : VisualScale ?
  children visualRgbas : VisualRgba ?
}

element VisualGlobal (xml="global") {
  cameraid         : int32
  orthographic     : bool
  fovy             : double
  ipd              : double
  azimuth          : double
  elevation        : double
  linewidth        : double
  glow             : double
  offwidth         : int32
  offheight        : int32
  realtime         : double
  ellipsoidinertia : bool
  bvactive         : bool
}

element VisualQuality (xml="quality") {
  shadowsize : int32
  offsamples : int32
  numslices  : int32
  numstacks  : int32
  numquads   : int32
}

element VisualHeadlight (xml="headlight") {
  ambient  : float[3]
  diffuse  : float[3]
  specular : float[3]
  active   : int32
}

element VisualMap (xml="map") {
  stiffness      : double
  stiffnessrot   : double
  force          : double
  torque         : double
  alpha          : double
  fogstart       : double
  fogend         : double
  znear          : double
  zfar           : double
  haze           : double
  shadowclip     : double
  shadowscale    : double
  actuatortendon : double
}

element VisualScale (xml="scale") {
  forcewidth     : double
  contactwidth   : double
  contactheight  : double
  connect        : double
  com            : double
  camera         : double
  light          : double
  selectpoint    : double
  jointlength    : double
  jointwidth     : double
  actuatorlength : double
  actuatorwidth  : double
  framelength    : double
  framewidth     : double
  constraint     : double
  slidercrank    : double
  frustum        : double
}

element VisualRgba (xml="rgba") {
  fog              : float[4]
  haze             : float[4]
  force            : float[4]
  inertia          : float[4]
  joint            : float[4]
  actuator         : float[4]
  actuatornegative : float[4]
  actuatorpositive : float[4]
  com              : float[4]
  camera           : float[4]
  light            : float[4]
  selectpoint      : float[4]
  connect          : float[4]
  contactpoint     : float[4]
  contactforce     : float[4]
  contactfriction  : float[4]
  contacttorque    : float[4]
  contactgap       : float[4]
  rangefinder      : float[4]
  constraint       : float[4]
  slidercrank      : float[4]
  crankbroken      : float[4]
  frustum          : float[4]
  bv               : float[4]
  bvactive         : float[4]
}

element Statistic {
  meaninertia : double
  meanmass    : double
  meansize    : double
  extent      : double
  center      : double[3]
}

element Default {
  dclass : string (xml="class")   # name of this default class
  children mesh : Mesh ?
  children material : Material ?
  children joint : Joint ?
  children geom : Geom ?
  children site : Site ?
  children camera : Camera ?
  children light : Light ?
  children pair : Pair ?
  children equality : EqualityDefault ?
  children tendon : TendonDefault ?
  children general : ActuatorGeneral ?
  children motor : Motor ?
  children position : Position ?
  children velocity : Velocity ?
  children intvelocity : IntVelocity ?
  children damper : Damper ?
  children cylinder : Cylinder ?
  children muscle : Muscle ?
  children adhesion : Adhesion ?
  children dcmotor : DcMotor ?
  children subclasses : Default *
}

element EqualityDefault (xml="equality", mjs=mjsEquality) {
  active : bool = true   # is equality initially active
  solref : double[0..2]   # solver reference
  solimp : double[0..5]   # solver impedance
}

element TendonDefault (xml="tendon", mjs=mjsTendon) {
  group          : int32   # group
  limited        : TriState   # does tendon have limits (mjtLimited)
  range          : double[2]   # length limits
  solreflimit    : double[0..2] (mjs=solref_limit)   # solver reference: tendon limits
  solimplimit    : double[0..5] (mjs=solimp_limit)   # solver impedance: tendon limits
  solreffriction : double[0..2] (mjs=solref_friction)   # solver reference: tendon friction
  solimpfriction : double[0..5] (mjs=solimp_friction)   # solver impedance: tendon friction
  frictionloss   : double   # friction loss
  springlength   : double[2] (resolver=springlength) = {-1, -1}   # spring resting length; {-1, -1}: use qpos_spring (canonical pair; a lone value is duplicated)
  width          : double = 0.003   # width for rendering
  material       : ref<Material>   # name of material for rendering
  margin         : double   # margin value for tendon limit detection
  stiffness      : double[0..3]   # stiffness coefficients (mjNPOLY+1)
  damping        : double[0..3]   # damping coefficients (mjNPOLY+1)
  rgba           : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  user           : double[] (mjs=userdata)   # user data
}

element Extension {
  children pluginDefs : PluginDef *
}

element PluginDef (xml="plugin") {
  plugin : string
  children pluginInstances : PluginInstance *
}

element PluginInstance (xml="instance") {
  name : string   # element name
  children config : Config *
}

element Config {
  key   : string
  value : string
}

element Custom {
  children numerics : Numeric *
  children texts : Text *
  children tuples : Tuple *
}

element Numeric {
  name : string   # element name
  data : double[] (aliases="size", resolver=numericdata)   # initialization data (canonical, materialized: zero-padded/truncated to the authored size)
}

element Text {
  name : string   # element name
  data : string   # text string
}

element Tuple {
  name : string   # element name
  children tupleElements : TupleElement *
}

element TupleElement (xml="element") {
  objtype : string
  objname : string (target_from=objtype)
  prm     : double
}

element Asset {
  children meshs : Mesh *
  children hfields : Hfield *
  children skins : Skin *
  children textures : Texture *
  children materials : Material *
  children modelAssets : ModelAsset *
}

element Mesh {
  name         : string   # element name
  dclass       : ref<Default> (xml="class")   # default class
  content_type : string   # content type of file
  file         : string   # mesh file
  vertex       : double[] (mjs=uservert)
  normal       : double[] (mjs=usernormal)
  texcoord     : float[] (mjs=usertexcoord)
  face         : int32[] (mjs=userface)
  refpos       : double[3]   # reference position
  refquat      : double[4]   # reference orientation
  scale        : double[3] = {1, 1, 1}   # rescale mesh
  smoothnormal : bool   # do not exclude large-angle faces from normals
  maxhullvert  : int32   # maximum vertex count for the convex hull
  inertia      : MeshInertia = legacy   # inertia type (convex, legacy, exact, shell)
  builtin      : MeshBuiltin
  params       : double[]
  material     : ref<Material>   # name of material
  children plugin : PluginRef *
}

element PluginRef (xml="plugin") {
  plugin   : string   # plugin name
  instance : ref<PluginInstance>   # plugin instance name
  children config : Config *
}

element Hfield (mjs=mjsHField) {
  name         : string   # element name
  content_type : string   # content type of file
  file         : string   # file: (nrow, ncol, [elevation data])
  nrow         : int32   # number of rows
  ncol         : int32   # number of columns
  size         : double[4]   # hfield size (ignore referencing geom size)
  elevation    : double[] (mjs=userdata)
}

element Skin {
  name     : string   # element name
  file     : string   # skin file
  material : ref<Material>   # name of material used for rendering
  rgba     : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  inflate  : float   # inflate in normal direction
  vertex   : float[] (mjs=vert)   # vertex positions
  texcoord : float[]   # texture coordinates
  face     : int32[]   # faces
  group    : int32   # group for visualization
  children bones : SkinBone *
}

element SkinBone (xml="bone") {
  body       : ref<Body>
  bindpos    : double[3]
  bindquat   : double[4]
  vertid     : int32[]
  vertweight : float[]
}

element Texture {
  name         : string   # element name
  type         : TextureType = cube   # texture type
  colorspace   : ColorSpace = auto   # colorspace
  content_type : string   # content type of file
  gridsize     : int32[2] = {1, 1}   # size of grid for composite file; (1,1)-repeat
  gridlayout   : string   # row-major: L,R,F,B,U,D for faces; . for unused
  fileright    : string   # image file for one cube face
  fileleft     : string   # image file for one cube face
  fileup       : string   # image file for one cube face
  filedown     : string   # image file for one cube face
  filefront    : string   # image file for one cube face
  fileback     : string   # image file for one cube face
  rgb1         : double[3] = {0.8, 0.8, 0.8}   # first color for builtin
  rgb2         : double[3] = {0.5, 0.5, 0.5}   # second color for builtin
  mark         : TextureMark   # mark type (mjtMark)
  markrgb      : double[3]   # mark color
  random       : double = 0.01   # probability of random dots
  width        : int32   # width in pixels
  height       : int32   # height in pixels (square for cube and skybox)
  hflip        : bool   # horizontal flip
  vflip        : bool   # vertical flip
  nchannel     : int32 = 3   # number of channels
  source       : variant TextureSource   # builtin generator or image file
}

element Material {
  name        : string   # element name
  dclass      : ref<Default> (xml="class")   # default class
  texrepeat   : float[2] = {1, 1}   # texture repetition for 2D mapping
  texuniform  : bool   # make texture cube uniform
  emission    : float   # emission
  specular    : float = 0.5   # specular
  shininess   : float = 0.5   # shininess
  reflectance : float   # reflectance
  metallic    : float   # metallic
  roughness   : float   # roughness
  rgba        : float[4] = {1, 1, 1, 1}   # rgba
  children layers : MaterialLayer *
}

element MaterialLayer (xml="layer") {
  texture : ref<Texture>
  role    : TexRole
}

element ModelAsset (xml="model") {
  name         : string   # element name
  file         : string
  content_type : string
}

element Body {
  use Posed
  name       : string   # element name
  childclass : ref<Default>   # default class applied to descendants
  mocap      : bool   # is this a mocap body
  gravcomp   : double   # gravity compensation
  sleep      : BodySleep   # sleep policy
  simple     : SimpleMode = auto   # simple body optimization (false/auto, FAuto_map)
  user       : double[] (mjs=userdata)   # user data
  children inertial : Inertial ?
  children subtree : BodyChildAny *
}

element Inertial (mjs=mjsBody) {
  pos         : double[3] (mjs=ipos)   # frame position
  mass        : double   # mass
  iquat       : double[4] (aliases="euler axisangle xyaxes zaxis", resolver=orientation, xml="quat")   # inertial frame orientation (canonical quat)
  diaginertia : double[3] (aliases="fullinertia", resolver=inertia, mjs=inertia)   # diagonal inertia (canonical; also accepts fullinertia)
}

element Joint {
  name               : string   # element name
  dclass             : ref<Default> (xml="class")   # default class
  type               : JointType = hinge   # joint type
  group              : int32   # group
  pos                : double[3]   # anchor position
  axis               : double[3] = {0, 0, 1}   # joint axis
  springdamper       : double[2]   # timeconst, dampratio
  limited            : TriState   # does joint have limits (mjtLimited)
  actuatorfrclimited : TriState (mjs=actfrclimited)   # are actuator forces on joint limited (mjtLimited)
  solreflimit        : double[0..2] (mjs=solref_limit)   # solver reference: joint limits
  solimplimit        : double[0..5] (mjs=solimp_limit)   # solver impedance: joint limits
  solreffriction     : double[0..2] (mjs=solref_friction)   # solver reference: dof friction
  solimpfriction     : double[0..5] (mjs=solimp_friction)   # solver impedance: dof friction
  stiffness          : double[0..3]   # stiffness coefficients (mjNPOLY+1)
  range              : double[2] (unit=angle)   # joint limits
  actuatorfrcrange   : double[2] (mjs=actfrcrange)   # actuator force limits
  actuatorgravcomp   : bool (mjs=actgravcomp)   # is gravcomp force applied via actuators
  margin             : double   # margin value for joint limit detection
  ref                : double (unit=angle)   # value at reference configuration: qpos0
  springref          : double (unit=angle)   # spring reference value: qpos_spring
  armature           : double   # armature inertia (mass for slider)
  damping            : double[0..3]   # damping coefficients (mjNPOLY+1)
  frictionloss       : double   # friction loss
  user               : double[] (mjs=userdata)   # user data
}

element FreeJoint (mjs=mjsJoint) {
  name  : string   # element name
  group : int32   # group
  align : TriState   # align free joint with body com (false/true/auto, TFAuto_map)
}

element Geom {
  use Posed
  name         : string   # element name
  dclass       : ref<Default> (xml="class")   # default class
  type         : GeomType = sphere   # geom type
  contype      : int32 = 1   # contact type
  conaffinity  : int32 = 1   # contact affinity
  condim       : int32 = 3   # contact dimensionality
  group        : int32   # group
  priority     : int32   # contact priority
  size         : double[0..3]   # type-specific size
  material     : ref<Material>   # name of material
  friction     : double[1..3] = {1, 0.005, 0.0001}   # one-sided friction coefficients: slide, roll, spin
  mass         : double   # used to compute density
  density      : double = 1000   # used to compute mass and inertia from volume or surface
  shellinertia : bool   # use shell (surface) instead of volume inertia
  solmix       : double = 1   # solver mixing for contact pairs
  solref       : double[0..2]   # solver reference
  solimp       : double[0..5]   # solver impedance
  margin       : double   # margin for contact detection
  gap          : double   # additional contact detection buffer
  surfacevel   : double[6] (lenient)   # surface velocity in local frame: linear, angular
  adhesion     : double   # adhesion coefficient (contact-driven adhesion)
  hfield       : ref<Hfield> (mjs=hfieldname)   # heightfield attached to geom
  mesh         : ref<Mesh> (mjs=meshname)   # mesh attached to geom
  fitscale     : double = 1   # scale mesh uniformly
  rgba         : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  fluidshape   : FluidShape
  fluidcoef    : double[0..5] (mjs=fluid_coefs) = {0.5, 0.25, 1.5, 1, 1}   # ellipsoid-fluid interaction coefs
  user         : double[] (mjs=userdata)   # user data
  shape        : variant GeomShape   # explicit size or fromto endpoints
  children plugin : PluginRef *
}

element Attach {
  model  : ref<ModelAsset>
  body   : string
  frame  : string   # attach into/onto a named frame (or self-attach)
  prefix : string
}

element Site {
  use Posed
  name     : string   # element name
  dclass   : ref<Default> (xml="class")   # default class
  type     : GeomType = sphere   # geom type
  group    : int32   # group
  material : ref<Material>   # name of material
  size     : double[0..3] = {0.005, 0.005, 0.005}   # geom size
  rgba     : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  user     : double[] (mjs=userdata)   # user data
  shape    : variant GeomShape   # explicit size or fromto endpoints
}

element Camera {
  use Posed
  name           : string   # element name
  dclass         : ref<Default> (xml="class")   # default class
  projection     : CameraProjection (mjs=proj)
  ipd            : double = 0.068   # inter-pupillary distance
  resolution     : int32[2] = {1, 1}   # resolution (pixel)
  output         : CameraOutput[]   # bit flags for output type
  mode           : CamLightMode = fixed   # tracking mode
  target         : ref<Body> (mjs=targetbody)   # target body for tracking/targeting
  focalpixel     : float[2] (mjs=focal_pixel)   # focal length (pixel)
  principal      : float[2] (mjs=principal_length)   # principal point (length)
  principalpixel : float[2] (mjs=principal_pixel)   # principal point (pixel)
  sensorsize     : float[2] (mjs=sensor_size)   # sensor size (length)
  user           : double[] (mjs=userdata)   # user data
  fovy           : double   # vertical field of view (deg; length if ortho)
  focal          : double[2] (mjs=focal_length)   # focal length (length)
}

element Light {
  name        : string   # element name
  dclass      : ref<Default> (xml="class")   # default class
  type        : LightType (aliases="directional", resolver=lighttype)   # type of light (canonical; also accepts legacy directional bool)
  castshadow  : bool = true   # does light cast shadows
  active      : bool = true   # is light active
  pos         : double[3]   # position
  dir         : double[3] = {0, 0, -1}   # direction
  bulbradius  : float = 0.02   # bulb radius, for soft shadows
  intensity   : float = 0   # intensity, in candelas
  range       : float = 10   # range of effectiveness
  attenuation : float[3]   # OpenGL attenuation (quadratic model)
  cutoff      : float = 45   # OpenGL cutoff
  exponent    : float = 10   # OpenGL exponent
  ambient     : float[3]   # ambient color
  diffuse     : float[3] = {0.7, 0.7, 0.7}   # diffuse color
  specular    : float[3] = {0.3, 0.3, 0.3}   # specular color
  mode        : CamLightMode = fixed   # tracking mode
  target      : ref<Body> (mjs=targetbody)   # target body for targeting
  texture     : ref<Texture>   # texture name for image lights
}

element Composite {
  prefix  : string
  type    : CompositeType
  count   : int32[0..3]
  offset  : double[3]
  vertex  : double[]   # vertex positions
  initial : string
  curve   : string
  size    : double[0..3]   # vertex bounding box half sizes in qpos0
  quat    : double[4]
  children compositeJoints : CompositeJoint *
  children compositeSkins : CompositeSkin ?
  children compositeGeoms : CompositeGeom ?
  children compositeSites : CompositeSite ?
  children plugin : PluginRef *
}

element CompositeJoint (xml="joint") {
  kind           : string
  group          : int32
  stiffness      : double
  damping        : double
  armature       : double
  solreffix      : double[0..2]
  solimpfix      : double[0..5]
  type           : JointType
  axis           : double[3]
  limited        : TriState
  range          : double[2]
  margin         : double
  solreflimit    : double[0..2]
  solimplimit    : double[0..5]
  frictionloss   : double
  solreffriction : double[0..2]
  solimpfriction : double[0..5]
}

element CompositeSkin (xml="skin") {
  texcoord : bool   # emit skin texture coordinates
  material : ref<Material>   # name of material used for rendering
  group    : int32   # group for visualization
  rgba     : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  inflate  : float   # inflate in normal direction
  subgrid  : int32
}

element CompositeGeom (xml="geom") {
  type        : GeomType = sphere   # geom type
  contype     : int32 = 1   # contact type
  conaffinity : int32 = 1   # contact affinity
  condim      : int32 = 3   # contact dimensionality
  group       : int32   # group
  priority    : int32   # contact priority
  size        : double[0..3]   # type-specific size
  material    : ref<Material>   # name of material
  rgba        : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  friction    : double[1..3] = {1, 0.005, 0.0001}   # one-sided friction coefficients: slide, roll, spin
  mass        : double   # used to compute density
  density     : double = 1000   # used to compute mass and inertia from volume or surface
  solmix      : double = 1   # solver mixing for contact pairs
  solref      : double[0..2]   # solver reference
  solimp      : double[0..5]   # solver impedance
  margin      : double   # margin for contact detection
  gap         : double   # additional contact detection buffer
  surfacevel  : double[6]   # surface velocity in local frame: linear, angular
  adhesion    : double   # adhesion coefficient (contact-driven adhesion)
}

element CompositeSite (xml="site") {
  group    : int32   # group
  size     : double[0..3] = {0.005, 0.005, 0.005}   # geom size
  material : ref<Material>   # name of material
  rgba     : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
}

element Flexcomp {
  name       : string   # element name
  type       : FlexcompType
  group      : int32   # group for visualization
  dim        : int32 = 2   # element dimensionality
  dof        : FlexDof
  count      : int32[3]
  cellcount  : int32[3] = {1, 1, 1}   # grid cell count for finite cell method
  spacing    : double[3]
  radius     : double = 0.005   # radius around primitive element
  rigid      : bool
  mass       : double
  inertiabox : double
  scale      : double[3]
  file       : string
  point      : double[]
  element    : int32[]   # element connectivity
  texcoord   : float[]   # vertex texture coordinates
  material   : ref<Material>   # name of material used for rendering
  rgba       : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  flatskin   : bool   # render flex skin with flat shading
  pos        : double[3]
  quat       : double[4] (aliases="euler axisangle xyaxes zaxis", resolver=orientation)   # orientation (canonical quat; also accepts euler/axisangle/xyaxes/zaxis)
  origin     : double[3]
  children flexcompEdges : FlexcompEdge ?
  children flexElasticitys : FlexElasticity ?
  children flexContacts : FlexContact ?
  children flexcompPins : FlexcompPin *
  children plugin : PluginRef *
}

element FlexcompEdge (xml="edge") {
  equality  : FlexEquality
  solref    : double[0..2]
  solimp    : double[0..5]
  stiffness : double
  damping   : double
}

element FlexElasticity (xml="elasticity") {
  young     : double   # Young's modulus
  poisson   : double   # Poisson's ratio
  damping   : double   # Rayleigh's damping
  thickness : double   # thickness (2D only)
  elastic2d : Elastic2D   # 2D passive forces; 0: none, 1: bending, 2: stretching, 3: both
}

element FlexContact (xml="contact") {
  contype      : int32 = 1   # contact type
  conaffinity  : int32 = 1   # contact affinity
  condim       : int32 = 3   # contact dimensionality
  priority     : int32   # contact priority
  friction     : double[1..3] = {1, 0.005, 0.0001}   # one-sided friction coefficients: slide, roll, spin
  solmix       : double = 1   # solver mixing for contact pairs
  solref       : double[0..2]   # solver reference
  solimp       : double[0..5]   # solver impedance
  margin       : double   # margin for contact detection
  gap          : double   # additional contact detection buffer
  internal     : bool = false   # enable internal collisions
  selfcollide  : FlexSelfCollide = auto   # mode for flex self collision
  activelayers : int32 = 1   # number of active element layers in 3D
  passive      : bool   # enable passive collisions
}

element FlexcompPin (xml="pin") {
  id        : int32[]
  range     : int32[]
  grid      : int32[]
  gridrange : int32[]
}

element Deformable {
  children flexs : Flex *
  children skins : Skin *
}

element Flex {
  name         : string   # element name
  group        : int32   # group for visualization
  dim          : int32 = 2   # element dimensionality
  radius       : double = 0.005   # radius around primitive element
  material     : ref<Material>   # name of material used for rendering
  rgba         : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  flatskin     : bool   # render flex skin with flat shading
  body         : ref<Body>[] (mjs=vertbody)
  vertex       : double[] (mjs=vert)   # vertex positions
  element      : int32[] (mjs=elem)   # element connectivity
  texcoord     : float[]   # vertex texture coordinates
  elemtexcoord : int32[]   # element texture coordinates
  node         : ref<Body>[] (mjs=nodebody)   # node body names
  cellcount    : int32[3] = {1, 1, 1}   # grid cell count for finite cell method
  dof          : FlexDof
  children flexContacts : FlexContact ?
  children flexEdges : FlexEdge ?
  children flexElasticitys : FlexElasticity ?
}

element FlexEdge (xml="edge") {
  stiffness : double
  damping   : double
}

element Contact {
  children pairs : Pair *
  children excludes : Exclude *
}

element Pair {
  name           : string   # element name
  dclass         : ref<Default> (xml="class")   # default class
  geom1          : ref<Geom> (mjs=geomname1)   # name of geom 1
  geom2          : ref<Geom> (mjs=geomname2)   # name of geom 2
  condim         : int32 = 3   # contact dimensionality
  friction       : double[0..5] = {1, 1, 0.005, 0.0001, 0.0001}   # full contact friction
  solref         : double[0..2]   # solver reference, normal direction
  solreffriction : double[0..2]
  solimp         : double[0..5]   # solver impedance
  gap            : double   # additional contact detection buffer
  margin         : double   # margin for contact detection
  adhesion       : double   # adhesion coefficient (contact-driven adhesion)
}

element Exclude {
  name  : string   # element name
  body1 : ref<Body> (mjs=bodyname1)   # name of body 1
  body2 : ref<Body> (mjs=bodyname2)   # name of body 2
}

element Equality {
  children equalities : EqualityAny *
}

element Connect (mjs=mjsEquality) {
  name   : string   # element name
  dclass : ref<Default> (xml="class")   # default class
  body1  : ref<Body>
  body2  : ref<Body>
  anchor : double[3]
  site1  : ref<Site>
  site2  : ref<Site>
  active : bool = true   # is equality initially active
  solref : double[0..2]   # solver reference
  solimp : double[0..5]   # solver impedance
}

element Weld (mjs=mjsEquality) {
  name        : string   # element name
  dclass      : ref<Default> (xml="class")   # default class
  body1       : ref<Body>
  body2       : ref<Body>
  relpose     : double[7]
  anchor      : double[3]
  site1       : ref<Site>
  site2       : ref<Site>
  active      : bool = true   # is equality initially active
  solref      : double[0..2]   # solver reference
  solimp      : double[0..5]   # solver impedance
  torquescale : double
}

element EqualityJoint (xml="joint", mjs=mjsEquality) {
  name     : string   # element name
  dclass   : ref<Default> (xml="class")   # default class
  joint1   : ref<Joint>
  joint2   : ref<Joint>
  polycoef : double[]
  active   : bool = true   # is equality initially active
  solref   : double[0..2]   # solver reference
  solimp   : double[0..5]   # solver impedance
}

element EqualityTendon (xml="tendon", mjs=mjsEquality) {
  name     : string   # element name
  dclass   : ref<Default> (xml="class")   # default class
  tendon1  : ref<TendonAny>
  tendon2  : ref<TendonAny>
  polycoef : double[]
  active   : bool = true   # is equality initially active
  solref   : double[0..2]   # solver reference
  solimp   : double[0..5]   # solver impedance
}

element EqualityFlex (xml="flex", mjs=mjsEquality) {
  name   : string   # element name
  dclass : ref<Default> (xml="class")   # default class
  flex   : ref<Flex>
  active : bool = true   # is equality initially active
  solref : double[0..2]   # solver reference
  solimp : double[0..5]   # solver impedance
}

element Flexvert (mjs=mjsEquality) {
  name   : string   # element name
  dclass : ref<Default> (xml="class")   # default class
  flex   : ref<Flex>
  active : bool = true   # is equality initially active
  solref : double[0..2]   # solver reference
  solimp : double[0..5]   # solver impedance
}

element Flexstrain (mjs=mjsEquality) {
  name   : string   # element name
  dclass : ref<Default> (xml="class")   # default class
  flex   : ref<Flex>
  cell   : double[3]
  active : bool = true   # is equality initially active
  solref : double[0..2]   # solver reference
  solimp : double[0..5]   # solver impedance
}

element Tendon {
  children tendons : TendonAny *
}

element Spatial (mjs=mjsTendon) {
  name               : string   # element name
  dclass             : ref<Default> (xml="class")   # default class
  group              : int32   # group
  limited            : TriState   # does tendon have limits (mjtLimited)
  actuatorfrclimited : TriState (mjs=actfrclimited)   # does tendon have actuator force limits
  range              : double[2]   # length limits
  actuatorfrcrange   : double[2] (mjs=actfrcrange)   # actuator force limits
  solreflimit        : double[0..2] (mjs=solref_limit)   # solver reference: tendon limits
  solimplimit        : double[0..5] (mjs=solimp_limit)   # solver impedance: tendon limits
  solreffriction     : double[0..2] (mjs=solref_friction)   # solver reference: tendon friction
  solimpfriction     : double[0..5] (mjs=solimp_friction)   # solver impedance: tendon friction
  frictionloss       : double   # friction loss
  springlength       : double[2] (resolver=springlength) = {-1, -1}   # spring resting length; {-1, -1}: use qpos_spring (canonical pair; a lone value is duplicated)
  width              : double = 0.003   # width for rendering
  material           : ref<Material>   # name of material for rendering
  margin             : double   # margin value for tendon limit detection
  stiffness          : double[0..3]   # stiffness coefficients
  damping            : double[0..3]   # damping coefficients
  armature           : double   # inertia associated with tendon velocity
  rgba               : float[4] = {0.5, 0.5, 0.5, 1}   # rgba when material is omitted
  user               : double[] (mjs=userdata)   # user data
  children path : PathItemAny *
}

element SpatialSite (xml="site") {
  site : ref<Site>
}

element SpatialGeom (xml="geom") {
  geom     : ref<Geom>
  sidesite : ref<Site>
}

element Pulley {
  divisor : double
}

element Fixed (mjs=mjsTendon) {
  name               : string   # element name
  dclass             : ref<Default> (xml="class")   # default class
  group              : int32   # group
  limited            : TriState   # does tendon have limits (mjtLimited)
  actuatorfrclimited : TriState (mjs=actfrclimited)   # does tendon have actuator force limits
  range              : double[2]   # length limits
  actuatorfrcrange   : double[2] (mjs=actfrcrange)   # actuator force limits
  solreflimit        : double[0..2] (mjs=solref_limit)   # solver reference: tendon limits
  solimplimit        : double[0..5] (mjs=solimp_limit)   # solver impedance: tendon limits
  solreffriction     : double[0..2] (mjs=solref_friction)   # solver reference: tendon friction
  solimpfriction     : double[0..5] (mjs=solimp_friction)   # solver impedance: tendon friction
  frictionloss       : double   # friction loss
  springlength       : double[2] (resolver=springlength) = {-1, -1}   # spring resting length; {-1, -1}: use qpos_spring (canonical pair; a lone value is duplicated)
  margin             : double   # margin value for tendon limit detection
  stiffness          : double[0..3]   # stiffness coefficients
  damping            : double[0..3]   # damping coefficients
  armature           : double   # inertia associated with tendon velocity
  user               : double[] (mjs=userdata)   # user data
  children fixedJoints : FixedJoint *
}

element FixedJoint (xml="joint") {
  joint : ref<Joint>
  coef  : double
}

element Actuator {
  children actuators : ActuatorAny *
}

element ActuatorGeneral (xml="general", mjs=mjsActuator) {
  use ActuatorHead
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  actlimited    : TriState   # are activation limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  actrange      : double[2]   # activation range
  lengthrange   : double[2]   # transmission length range
  use Transmission
  body          : ref<Body>
  actdim        : int32   # number of activation variables
  input         : SO3Input   # SO3 control chart (expmap/quat); sets ctrlspec
  dyntype       : DynType = none   # dynamics type
  gaintype      : GainType = fixed   # gain type
  biastype      : BiasType = none   # bias type
  dynprm        : double[0..10]   # dynamics parameters
  gainprm       : double[0..10]   # gain parameters
  biasprm       : double[0..10]   # bias parameters
  actearly      : bool   # apply next activations to qfrc
}

element Motor (mjs=mjsActuator) {
  use ActuatorHead
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  lengthrange   : double[2]   # transmission length range
  use Transmission
}

element Position (mjs=mjsActuator) {
  use ActuatorHead
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  inheritrange  : double   # automatic range setting for position and intvelocity
  forcerange    : double[2]   # force range
  lengthrange   : double[2]   # transmission length range
  use Transmission
  kp            : double   # position feedback gain
  kv            : double   # velocity feedback gain
  dampratio     : double   # damping ratio, in units of critical damping
  timeconst     : double   # time constant of the activation dynamics
}

element Velocity (mjs=mjsActuator) {
  use ActuatorHead
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  lengthrange   : double[2]   # transmission length range
  use Transmission
  kv            : double   # velocity feedback gain
}

element IntVelocity (mjs=mjsActuator) {
  use ActuatorHead
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  actlimited    : TriState   # are activation limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  actrange      : double[2]   # activation range
  inheritrange  : double   # automatic range setting for position and intvelocity
  lengthrange   : double[2]   # transmission length range
  use Transmission
  kp            : double   # position feedback gain
  kv            : double   # velocity feedback gain
  dampratio     : double   # damping ratio, in units of critical damping
}

element Orientation (mjs=mjsActuator) {
  use ActuatorHead
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  user          : double[] (mjs=userdata)   # user data
  joint         : ref<Joint>
  site          : ref<Site>   # site transmission target
  refsite       : ref<Site>   # reference site, for site transmission
  kp            : double   # position feedback gain
  kv            : double   # velocity feedback gain
  dampratio     : double   # damping ratio, in units of critical damping
  input         : SO3Input   # SO3 control chart (expmap/quat); sets ctrlspec
}

element Damper (mjs=mjsActuator) {
  use ActuatorHead
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  lengthrange   : double[2]   # transmission length range
  use Transmission
  kv            : double   # velocity feedback gain
}

element Cylinder (mjs=mjsActuator) {
  use ActuatorHead
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  lengthrange   : double[2]   # transmission length range
  use Transmission
  timeconst     : double   # time constant of the activation dynamics
  area          : double (aliases="diameter", resolver=cylinderarea)   # cylinder area (canonical; also accepts diameter, area = pi/4 d^2)
  bias          : double[3]   # cylinder bias parameters
}

element Muscle (mjs=mjsActuator) {
  use ActuatorHead
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  lengthrange   : double[2]   # transmission length range
  gear          : double[0..6] = {1}   # length and transmitted force scaling
  damping       : double[0..3]   # damping coefficients
  armature      : double   # armature inertia
  cranklength   : double   # crank length, for slider-crank
  user          : double[] (mjs=userdata)   # user data
  joint         : ref<Joint>
  jointinparent : ref<Joint>
  tendon        : ref<TendonAny>
  slidersite    : ref<Site>   # site defining cylinder, for slider-crank
  cranksite     : ref<Site>
  timeconst     : double[2]   # time constant of the activation dynamics
  tausmooth     : double
  range         : double[2]   # muscle operating length range
  force         : double   # peak active force (muscle); <0: automatic
  scale         : double   # muscle force = scale / acc0
  lmin          : double   # lower bound on muscle operating length
  lmax          : double   # upper bound on muscle operating length
  vmax          : double   # shortening velocity at which force drops to zero
  fpmax         : double   # peak passive force at length lmax
  fvmax         : double   # active force at saturating lengthening velocity
}

element Adhesion (mjs=mjsActuator) {
  use ActuatorHead
  forcelimited : TriState   # are force limits defined (mjtLimited)
  ctrlrange    : double[2]   # control range
  forcerange   : double[2]   # force range
  user         : double[] (mjs=userdata)   # user data
  body         : ref<Body>
  gain         : double   # adhesion gain
}

element DcMotor (mjs=mjsActuator) {
  use ActuatorHead
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  lengthrange   : double[2]   # transmission length range
  use Transmission
  motorconst    : double[0..2]   # motor torque constant
  resistance    : double   # armature resistance
  nominal       : double[0..3]   # nominal supply voltage
  saturation    : double[0..3]   # voltage saturation
  inductance    : double[0..2]   # armature inductance
  cogging       : double[0..3]   # cogging torque amplitude
  controller    : double[0..6]   # controller gains
  thermal       : double[0..6]   # thermal model parameters
  lugre         : double[0..5]   # LuGre friction parameters
  input         : DcMotorInput
}

element ActuatorPlugin (xml="plugin", mjs=mjsActuator) {
  name          : string   # element name
  dclass        : ref<Default> (xml="class")   # default class
  plugin        : string   # plugin name
  instance      : ref<PluginInstance>
  group         : int32   # group
  nsample       : int32   # number of samples in history buffer
  interp        : InterpType   # interpolation order (0=ZOH, 1=linear, 2=cubic)
  delay         : double   # delay time in seconds; 0: no delay
  ctrllimited   : TriState   # are control limits defined (mjtLimited)
  forcelimited  : TriState   # are force limits defined (mjtLimited)
  actlimited    : TriState   # are activation limits defined (mjtLimited)
  ctrlrange     : double[2]   # control range
  forcerange    : double[2]   # force range
  actrange      : double[2]   # activation range
  lengthrange   : double[2]   # transmission length range
  gear          : double[0..6] = {1}   # length and transmitted force scaling
  damping       : double[0..3]   # damping coefficients
  armature      : double   # armature inertia
  cranklength   : double   # crank length, for slider-crank
  joint         : ref<Joint>
  jointinparent : ref<Joint>
  site          : ref<Site>
  actdim        : int32   # number of activation variables
  dyntype       : DynType   # dynamics type
  dynprm        : double[0..10]   # dynamics parameters
  tendon        : ref<TendonAny>
  cranksite     : ref<Site>
  slidersite    : ref<Site>   # site defining cylinder, for slider-crank
  user          : double[] (mjs=userdata)   # user data
  actearly      : bool   # apply next activations to qfrc
  children config : Config *
}

element Sensor {
  children sensors : SensorAny *
}

element Touch (mjs=mjsSensor) {
  name     : string   # element name
  site     : ref<Site>
  use SensorTail
}

element Accelerometer (mjs=mjsSensor) {
  name     : string   # element name
  site     : ref<Site>
  use SensorTail
}

element Velocimeter (mjs=mjsSensor) {
  name     : string   # element name
  site     : ref<Site>
  use SensorTail
}

element Gyro (mjs=mjsSensor) {
  name     : string   # element name
  site     : ref<Site>
  use SensorTail
}

element Force (mjs=mjsSensor) {
  name     : string   # element name
  site     : ref<Site>
  use SensorTail
}

element Torque (mjs=mjsSensor) {
  name     : string   # element name
  site     : ref<Site>
  use SensorTail
}

element Magnetometer (mjs=mjsSensor) {
  name     : string   # element name
  site     : ref<Site>
  use SensorTail
}

element Camprojection (mjs=mjsSensor) {
  name     : string   # element name
  site     : ref<Site>
  camera   : ref<Camera>
  use SensorTail
}

element Rangefinder (mjs=mjsSensor) {
  name     : string   # element name
  site     : ref<Site>
  camera   : ref<Camera>
  data     : RayData[]
  use SensorTail
}

element Jointpos (mjs=mjsSensor) {
  name     : string   # element name
  joint    : ref<Joint>
  use SensorTail
}

element Jointvel (mjs=mjsSensor) {
  name     : string   # element name
  joint    : ref<Joint>
  use SensorTail
}

element Tendonpos (mjs=mjsSensor) {
  name     : string   # element name
  tendon   : ref<TendonAny>
  use SensorTail
}

element Tendonvel (mjs=mjsSensor) {
  name     : string   # element name
  tendon   : ref<TendonAny>
  use SensorTail
}

element Actuatorpos (mjs=mjsSensor) {
  name     : string   # element name
  actuator : ref<ActuatorAny>
  use SensorTail
}

element Actuatorvel (mjs=mjsSensor) {
  name     : string   # element name
  actuator : ref<ActuatorAny>
  use SensorTail
}

element Actuatorfrc (mjs=mjsSensor) {
  name     : string   # element name
  actuator : ref<ActuatorAny>
  use SensorTail
}

element Jointactuatorfrc (mjs=mjsSensor) {
  name     : string   # element name
  joint    : ref<Joint>
  use SensorTail
}

element Tendonactuatorfrc (mjs=mjsSensor) {
  name     : string   # element name
  tendon   : ref<TendonAny>
  use SensorTail
}

element Ballquat (mjs=mjsSensor) {
  name     : string   # element name
  joint    : ref<Joint>
  use SensorTail
}

element Ballangvel (mjs=mjsSensor) {
  name     : string   # element name
  joint    : ref<Joint>
  use SensorTail
}

element Jointlimitpos (mjs=mjsSensor) {
  name     : string   # element name
  joint    : ref<Joint>
  use SensorTail
}

element Jointlimitvel (mjs=mjsSensor) {
  name     : string   # element name
  joint    : ref<Joint>
  use SensorTail
}

element Jointlimitfrc (mjs=mjsSensor) {
  name     : string   # element name
  joint    : ref<Joint>
  use SensorTail
}

element Tendonlimitpos (mjs=mjsSensor) {
  name     : string   # element name
  tendon   : ref<TendonAny>
  use SensorTail
}

element Tendonlimitvel (mjs=mjsSensor) {
  name     : string   # element name
  tendon   : ref<TendonAny>
  use SensorTail
}

element Tendonlimitfrc (mjs=mjsSensor) {
  name     : string   # element name
  tendon   : ref<TendonAny>
  use SensorTail
}

element Framepos (mjs=mjsSensor) {
  name     : string   # element name
  objtype  : string
  objname  : string (target_from=objtype)
  reftype  : string
  refname  : string (target_from=reftype)
  use SensorTail
}

element Framequat (mjs=mjsSensor) {
  name     : string   # element name
  objtype  : string
  objname  : string (target_from=objtype)
  reftype  : string
  refname  : string (target_from=reftype)
  use SensorTail
}

element Framexaxis (mjs=mjsSensor) {
  name     : string   # element name
  objtype  : string
  objname  : string (target_from=objtype)
  reftype  : string
  refname  : string (target_from=reftype)
  use SensorTail
}

element Frameyaxis (mjs=mjsSensor) {
  name     : string   # element name
  objtype  : string
  objname  : string (target_from=objtype)
  reftype  : string
  refname  : string (target_from=reftype)
  use SensorTail
}

element Framezaxis (mjs=mjsSensor) {
  name     : string   # element name
  objtype  : string
  objname  : string (target_from=objtype)
  reftype  : string
  refname  : string (target_from=reftype)
  use SensorTail
}

element Framelinvel (mjs=mjsSensor) {
  name     : string   # element name
  objtype  : string
  objname  : string (target_from=objtype)
  reftype  : string
  refname  : string (target_from=reftype)
  use SensorTail
}

element Frameangvel (mjs=mjsSensor) {
  name     : string   # element name
  objtype  : string
  objname  : string (target_from=objtype)
  reftype  : string
  refname  : string (target_from=reftype)
  use SensorTail
}

element Framelinacc (mjs=mjsSensor) {
  name     : string   # element name
  objtype  : string
  objname  : string (target_from=objtype)
  use SensorTail
}

element Frameangacc (mjs=mjsSensor) {
  name     : string   # element name
  objtype  : string
  objname  : string (target_from=objtype)
  use SensorTail
}

element Subtreecom (mjs=mjsSensor) {
  name     : string   # element name
  body     : ref<Body>
  use SensorTail
}

element Subtreelinvel (mjs=mjsSensor) {
  name     : string   # element name
  body     : ref<Body>
  use SensorTail
}

element Subtreeangmom (mjs=mjsSensor) {
  name     : string   # element name
  body     : ref<Body>
  use SensorTail
}

element Insidesite (mjs=mjsSensor) {
  name     : string   # element name
  site     : ref<Site>
  objtype  : string
  objname  : string (target_from=objtype)
  use SensorTail
}

element Distance (mjs=mjsSensor) {
  name     : string   # element name
  geom1    : ref<Geom>
  geom2    : ref<Geom>
  body1    : ref<Body>
  body2    : ref<Body>
  use SensorTail
}

element Normal (mjs=mjsSensor) {
  name     : string   # element name
  geom1    : ref<Geom>
  geom2    : ref<Geom>
  body1    : ref<Body>
  body2    : ref<Body>
  use SensorTail
}

element Fromto (mjs=mjsSensor) {
  name     : string   # element name
  geom1    : ref<Geom>
  geom2    : ref<Geom>
  body1    : ref<Body>
  body2    : ref<Body>
  use SensorTail
}

element SensorContact (xml="contact", mjs=mjsSensor) {
  name     : string   # element name
  geom1    : ref<Geom>
  geom2    : ref<Geom>
  body1    : ref<Body>
  body2    : ref<Body>
  subtree1 : ref<Body>
  subtree2 : ref<Body>
  site     : ref<Site>
  num      : int32
  data     : ContactData[]
  reduce   : ContactReduce
  use SensorTail
}

element EPotential (xml="e_potential", mjs=mjsSensor) {
  name     : string   # element name
  use SensorTail
}

element EKinetic (xml="e_kinetic", mjs=mjsSensor) {
  name     : string   # element name
  use SensorTail
}

element Clock (mjs=mjsSensor) {
  name     : string   # element name
  use SensorTail
}

element Tactile (mjs=mjsSensor) {
  name     : string   # element name
  geom     : ref<Geom>
  mesh     : ref<Mesh>
  nsample  : int32
  interp   : InterpType
  delay    : double
  interval : double[0..2]
  user     : double[] (mjs=userdata)
}

element SensorUser (xml="user", mjs=mjsSensor) {
  name      : string   # element name
  objtype   : string
  objname   : string (target_from=objtype)
  datatype  : DataType
  needstage : NeedStage
  dim       : int32
  cutoff    : double
  noise     : double
  user      : double[] (mjs=userdata)
}

element SensorPlugin (xml="plugin", mjs=mjsSensor) {
  name     : string   # element name
  plugin   : string
  instance : ref<PluginInstance>
  cutoff   : double
  objtype  : string
  objname  : string (target_from=objtype)
  reftype  : string
  refname  : string (target_from=reftype)
  user     : double[] (mjs=userdata)
  children config : Config *
}

element Keyframe {
  children keys : Key *
}

element Key {
  name  : string   # element name
  time  : double   # time
  qpos  : double[]   # qpos
  qvel  : double[]   # qvel
  act   : double[]   # act
  mpos  : double[]   # mocap pos
  mquat : double[]   # mocap quat
  ctrl  : double[]   # ctrl
}

element Frame {
  use Posed
  name   : string
  dclass : ref<Default> (xml="class", mjs=childclass)   # childclass applied to descendants
  children inertial : Inertial ?
  children subtree : BodyChildAny *
}

element Replicate {
  count      : int32 (required)   # number of copies to generate
  offset     : double[3]   # position offset accumulated per copy
  euler      : double[3] (unit=angle)   # rotation offset accumulated per copy
  sep        : string   # separator for the cloned element name suffix
  prefix     : string   # prefix applied to cloned element names
  childclass : ref<Default>   # default class applied to descendants
  children inertial : Inertial ?
  children subtree : BodyChildAny *
}

